/*
contributors: Patricio Gonzalez Vivo
description: | 
    RGB colors from Ferrario's oil paint colors. 
    Based on https://sensuallogic.com/artistcolordata
*/

#ifndef FERRARIO_OIL_TITANIUM_WHITE
#define FERRARIO_OIL_TITANIUM_WHITE vec3(0.969, 0.965, 0.957)
#endif
#ifndef TITANIUM_WHITE
#define TITANIUM_WHITE FERRARIO_OIL_TITANIUM_WHITE
#endif

#ifndef FERRARIO_OIL_CADMIUM_YELLOW_LEMON
#define FERRARIO_OIL_CADMIUM_YELLOW_LEMON vec3(0.984, 0.827, 0.000)
#endif
#ifndef CADMIUM_YELLOW_LEMON
#define CADMIUM_YELLOW_LEMON FERRARIO_OIL_CADMIUM_YELLOW_LEMON
#endif

#ifndef FERRARIO_OIL_CADMIUM_YELLOW_LIGHT
#define FERRARIO_OIL_CADMIUM_YELLOW_LIGHT vec3(1.000, 0.769, 0.000)
#endif
#ifndef CADMIUM_YELLOW_LIGHT
#define CADMIUM_YELLOW_LIGHT FERRARIO_OIL_CADMIUM_YELLOW_LIGHT
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_YELLOW_DEEP
#define FERRARIO_OIL_FERRARIO1919_YELLOW_DEEP vec3(1.000, 0.592, 0.000)
#endif
#ifndef FERRARIO1919_YELLOW_DEEP
#define FERRARIO1919_YELLOW_DEEP FERRARIO_OIL_FERRARIO1919_YELLOW_DEEP
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_ORANGE
#define FERRARIO_OIL_FERRARIO1919_ORANGE vec3(1.000, 0.451, 0.000)
#endif
#ifndef FERRARIO1919_ORANGE
#define FERRARIO1919_ORANGE FERRARIO_OIL_FERRARIO1919_ORANGE
#endif

#ifndef FERRARIO_OIL_CADMIUM_RED_LIGHT
#define FERRARIO_OIL_CADMIUM_RED_LIGHT vec3(0.910, 0.243, 0.000)
#endif
#ifndef CADMIUM_RED_LIGHT
#define CADMIUM_RED_LIGHT FERRARIO_OIL_CADMIUM_RED_LIGHT
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_RED
#define FERRARIO_OIL_FERRARIO1919_RED vec3(0.753, 0.000, 0.000)
#endif
#ifndef FERRARIO1919_RED
#define FERRARIO1919_RED FERRARIO_OIL_FERRARIO1919_RED
#endif

#ifndef FERRARIO_OIL_MAGENTA
#define FERRARIO_OIL_MAGENTA vec3(0.506, 0.031, 0.118)
#endif
#ifndef MAGENTA
#define MAGENTA FERRARIO_OIL_MAGENTA
#endif

#ifndef FERRARIO_OIL_ALIZARINE_MADDER
#define FERRARIO_OIL_ALIZARINE_MADDER vec3(0.349, 0.000, 0.067)
#endif
#ifndef ALIZARINE_MADDER
#define ALIZARINE_MADDER FERRARIO_OIL_ALIZARINE_MADDER
#endif

#ifndef FERRARIO_OIL_MAGENTA_LAKE
#define FERRARIO_OIL_MAGENTA_LAKE vec3(0.451, 0.000, 0.118)
#endif
#ifndef MAGENTA_LAKE
#define MAGENTA_LAKE FERRARIO_OIL_MAGENTA_LAKE
#endif

#ifndef FERRARIO_OIL_MANGANESE_VIOLET
#define FERRARIO_OIL_MANGANESE_VIOLET vec3(0.271, 0.086, 0.294)
#endif
#ifndef MANGANESE_VIOLET
#define MANGANESE_VIOLET FERRARIO_OIL_MANGANESE_VIOLET
#endif

#ifndef FERRARIO_OIL_ULTRAMARINE_BLUE
#define FERRARIO_OIL_ULTRAMARINE_BLUE vec3(0.043, 0.031, 0.133)
#endif
#ifndef ULTRAMARINE_BLUE
#define ULTRAMARINE_BLUE FERRARIO_OIL_ULTRAMARINE_BLUE
#endif

#ifndef FERRARIO_OIL_ULTRAMARINE_SKY_BLUE
#define FERRARIO_OIL_ULTRAMARINE_SKY_BLUE vec3(0.051, 0.035, 0.176)
#endif
#ifndef ULTRAMARINE_SKY_BLUE
#define ULTRAMARINE_SKY_BLUE FERRARIO_OIL_ULTRAMARINE_SKY_BLUE
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_BLUE_RED_HUE
#define FERRARIO_OIL_FERRARIO1919_BLUE_RED_HUE vec3(0.051, 0.063, 0.188)
#endif
#ifndef FERRARIO1919_BLUE_RED_HUE
#define FERRARIO1919_BLUE_RED_HUE FERRARIO_OIL_FERRARIO1919_BLUE_RED_HUE
#endif

#ifndef FERRARIO_OIL_COBALT_BLUE_LIGHT
#define FERRARIO_OIL_COBALT_BLUE_LIGHT vec3(0.000, 0.588, 0.647)
#endif
#ifndef COBALT_BLUE_LIGHT
#define COBALT_BLUE_LIGHT FERRARIO_OIL_COBALT_BLUE_LIGHT
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_BLUE_GREEN_HUE
#define FERRARIO_OIL_FERRARIO1919_BLUE_GREEN_HUE vec3(0.075, 0.082, 0.231)
#endif
#ifndef FERRARIO1919_BLUE_GREEN_HUE
#define FERRARIO1919_BLUE_GREEN_HUE FERRARIO_OIL_FERRARIO1919_BLUE_GREEN_HUE
#endif

#ifndef FERRARIO_OIL_PRUSSIAN_BLUE
#define FERRARIO_OIL_PRUSSIAN_BLUE vec3(0.043, 0.063, 0.141)
#endif
#ifndef PRUSSIAN_BLUE
#define PRUSSIAN_BLUE FERRARIO_OIL_PRUSSIAN_BLUE
#endif

#ifndef FERRARIO_OIL_CERULEAN_BLUE
#define FERRARIO_OIL_CERULEAN_BLUE vec3(0.000, 0.384, 0.573)
#endif
#ifndef CERULEAN_BLUE
#define CERULEAN_BLUE FERRARIO_OIL_CERULEAN_BLUE
#endif

#ifndef FERRARIO_OIL_COBALT_TURQUOISE
#define FERRARIO_OIL_COBALT_TURQUOISE vec3(0.000, 0.588, 0.647)
#endif
#ifndef COBALT_TURQUOISE
#define COBALT_TURQUOISE FERRARIO_OIL_COBALT_TURQUOISE
#endif

#ifndef FERRARIO_OIL_COBALT_GREEN_LIGHT
#define FERRARIO_OIL_COBALT_GREEN_LIGHT vec3(0.000, 0.392, 0.384)
#endif
#ifndef COBALT_GREEN_LIGHT
#define COBALT_GREEN_LIGHT FERRARIO_OIL_COBALT_GREEN_LIGHT
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_GREEN_BLUE_HUE
#define FERRARIO_OIL_FERRARIO1919_GREEN_BLUE_HUE vec3(0.000, 0.133, 0.137)
#endif
#ifndef FERRARIO1919_GREEN_BLUE_HUE
#define FERRARIO1919_GREEN_BLUE_HUE FERRARIO_OIL_FERRARIO1919_GREEN_BLUE_HUE
#endif

#ifndef FERRARIO_OIL_EMERALD_GREEN
#define FERRARIO_OIL_EMERALD_GREEN vec3(0.000, 0.271, 0.227)
#endif
#ifndef EMERALD_GREEN
#define EMERALD_GREEN FERRARIO_OIL_EMERALD_GREEN
#endif

#ifndef FERRARIO_OIL_FERRARIO1919_GREEN_YELLOW_HUE
#define FERRARIO_OIL_FERRARIO1919_GREEN_YELLOW_HUE vec3(0.000, 0.184, 0.129)
#endif
#ifndef FERRARIO1919_GREEN_YELLOW_HUE
#define FERRARIO1919_GREEN_YELLOW_HUE FERRARIO_OIL_FERRARIO1919_GREEN_YELLOW_HUE
#endif

#ifndef FERRARIO_OIL_PERMANENT_GREEN
#define FERRARIO_OIL_PERMANENT_GREEN vec3(0.000, 0.439, 0.227)
#endif
#ifndef PERMANENT_GREEN
#define PERMANENT_GREEN FERRARIO_OIL_PERMANENT_GREEN
#endif

#ifndef FERRARIO_OIL_CADMIUM_GREEN_LIGHT
#define FERRARIO_OIL_CADMIUM_GREEN_LIGHT vec3(0.463, 0.776, 0.000)
#endif
#ifndef CADMIUM_GREEN_LIGHT
#define CADMIUM_GREEN_LIGHT FERRARIO_OIL_CADMIUM_GREEN_LIGHT
#endif

#ifndef FERRARIO_OIL_LEMON_OCHRE
#define FERRARIO_OIL_LEMON_OCHRE vec3(0.725, 0.494, 0.102)
#endif
#ifndef LEMON_OCHRE
#define LEMON_OCHRE FERRARIO_OIL_LEMON_OCHRE
#endif

#ifndef FERRARIO_OIL_TRANSPARENT_MARS_YELLOW
#define FERRARIO_OIL_TRANSPARENT_MARS_YELLOW vec3(0.533, 0.353, 0.161)
#endif
#ifndef TRANSPARENT_MARS_YELLOW
#define TRANSPARENT_MARS_YELLOW FERRARIO_OIL_TRANSPARENT_MARS_YELLOW
#endif

#ifndef FERRARIO_OIL_BURNT_UMBER
#define FERRARIO_OIL_BURNT_UMBER vec3(0.165, 0.106, 0.071)
#endif
#ifndef BURNT_UMBER
#define BURNT_UMBER FERRARIO_OIL_BURNT_UMBER
#endif

#ifndef FERRARIO_OIL_TRANSPARENT_BROWN
#define FERRARIO_OIL_TRANSPARENT_BROWN vec3(0.200, 0.086, 0.051)
#endif
#ifndef TRANSPARENT_BROWN
#define TRANSPARENT_BROWN FERRARIO_OIL_TRANSPARENT_BROWN
#endif

#ifndef FERRARIO_OIL_IVORY_BLACK
#define FERRARIO_OIL_IVORY_BLACK vec3(0.086, 0.082, 0.086)
#endif
#ifndef IVORY_BLACK
#define IVORY_BLACK FERRARIO_OIL_IVORY_BLACK
#endif

