/*
contributors: Patricio Gonzalez Vivo
description: | 
    RGB colors from Rembrandt's oil paint colors. 
    Based on https://sensuallogic.com/artistcolordata
*/

#ifndef REMBRANDT_OIL_TITANIUM_WHITE
#define REMBRANDT_OIL_TITANIUM_WHITE vec3(0.992, 0.996, 0.976)
#endif
#ifndef TITANIUM_WHITE
#define TITANIUM_WHITE REMBRANDT_OIL_TITANIUM_WHITE
#endif

#ifndef REMBRANDT_OIL_CADM._YELLOW_LEMON
#define REMBRANDT_OIL_CADM._YELLOW_LEMON vec3(0.973, 0.871, 0.008)
#endif
#ifndef CADM._YELLOW_LEMON
#define CADM._YELLOW_LEMON REMBRANDT_OIL_CADM._YELLOW_LEMON
#endif

#ifndef REMBRANDT_OIL_CADMIUM_ORANGE
#define REMBRANDT_OIL_CADMIUM_ORANGE vec3(1.000, 0.431, 0.055)
#endif
#ifndef CADMIUM_ORANGE
#define CADMIUM_ORANGE REMBRANDT_OIL_CADMIUM_ORANGE
#endif

#ifndef REMBRANDT_OIL_YELLOW_OCHRE
#define REMBRANDT_OIL_YELLOW_OCHRE vec3(0.675, 0.467, 0.149)
#endif
#ifndef YELLOW_OCHRE
#define YELLOW_OCHRE REMBRANDT_OIL_YELLOW_OCHRE
#endif

#ifndef REMBRANDT_OIL_ORANGE_OCHRE
#define REMBRANDT_OIL_ORANGE_OCHRE vec3(0.576, 0.298, 0.173)
#endif
#ifndef ORANGE_OCHRE
#define ORANGE_OCHRE REMBRANDT_OIL_ORANGE_OCHRE
#endif

#ifndef REMBRANDT_OIL_RAW_SIENNA
#define REMBRANDT_OIL_RAW_SIENNA vec3(0.545, 0.373, 0.184)
#endif
#ifndef RAW_SIENNA
#define RAW_SIENNA REMBRANDT_OIL_RAW_SIENNA
#endif

#ifndef REMBRANDT_OIL_CADMIUM_YELLOW_M
#define REMBRANDT_OIL_CADMIUM_YELLOW_M vec3(1.000, 0.753, 0.000)
#endif
#ifndef CADMIUM_YELLOW_M
#define CADMIUM_YELLOW_M REMBRANDT_OIL_CADMIUM_YELLOW_M
#endif

#ifndef REMBRANDT_OIL_CADMIUM_RED_L
#define REMBRANDT_OIL_CADMIUM_RED_L vec3(0.906, 0.220, 0.031)
#endif
#ifndef CADMIUM_RED_L
#define CADMIUM_RED_L REMBRANDT_OIL_CADMIUM_RED_L
#endif

#ifndef REMBRANDT_OIL_CADMIUM_RED_D
#define REMBRANDT_OIL_CADMIUM_RED_D vec3(0.714, 0.082, 0.137)
#endif
#ifndef CADMIUM_RED_D
#define CADMIUM_RED_D REMBRANDT_OIL_CADMIUM_RED_D
#endif

#ifndef REMBRANDT_OIL_VERMILION
#define REMBRANDT_OIL_VERMILION vec3(0.961, 0.271, 0.000)
#endif
#ifndef VERMILION
#define VERMILION REMBRANDT_OIL_VERMILION
#endif

#ifndef REMBRANDT_OIL_CADMIUM_RED_M
#define REMBRANDT_OIL_CADMIUM_RED_M vec3(0.804, 0.149, 0.118)
#endif
#ifndef CADMIUM_RED_M
#define CADMIUM_RED_M REMBRANDT_OIL_CADMIUM_RED_M
#endif

#ifndef REMBRANDT_OIL_CARMINE
#define REMBRANDT_OIL_CARMINE vec3(0.439, 0.067, 0.110)
#endif
#ifndef CARMINE
#define CARMINE REMBRANDT_OIL_CARMINE
#endif

#ifndef REMBRANDT_OIL_SCARLET
#define REMBRANDT_OIL_SCARLET vec3(0.561, 0.063, 0.137)
#endif
#ifndef SCARLET
#define SCARLET REMBRANDT_OIL_SCARLET
#endif

#ifndef REMBRANDT_OIL_PERM.MADDER_D
#define REMBRANDT_OIL_PERM.MADDER_D vec3(0.388, 0.118, 0.169)
#endif
#ifndef PERM.MADDER_D
#define PERM.MADDER_D REMBRANDT_OIL_PERM.MADDER_D
#endif

#ifndef REMBRANDT_OIL_VENETIAN_RED
#define REMBRANDT_OIL_VENETIAN_RED vec3(0.471, 0.188, 0.149)
#endif
#ifndef VENETIAN_RED
#define VENETIAN_RED REMBRANDT_OIL_VENETIAN_RED
#endif

#ifndef REMBRANDT_OIL_QUINACRIDONE_ROSE
#define REMBRANDT_OIL_QUINACRIDONE_ROSE vec3(0.498, 0.102, 0.165)
#endif
#ifndef QUINACRIDONE_ROSE
#define QUINACRIDONE_ROSE REMBRANDT_OIL_QUINACRIDONE_ROSE
#endif

#ifndef REMBRANDT_OIL_RAW_UMBER
#define REMBRANDT_OIL_RAW_UMBER vec3(0.196, 0.169, 0.149)
#endif
#ifndef RAW_UMBER
#define RAW_UMBER REMBRANDT_OIL_RAW_UMBER
#endif

#ifndef REMBRANDT_OIL_BURNT_UMBER
#define REMBRANDT_OIL_BURNT_UMBER vec3(0.235, 0.157, 0.137)
#endif
#ifndef BURNT_UMBER
#define BURNT_UMBER REMBRANDT_OIL_BURNT_UMBER
#endif

#ifndef REMBRANDT_OIL_BURNT_SIENNA
#define REMBRANDT_OIL_BURNT_SIENNA vec3(0.396, 0.220, 0.184)
#endif
#ifndef BURNT_SIENNA
#define BURNT_SIENNA REMBRANDT_OIL_BURNT_SIENNA
#endif

#ifndef REMBRANDT_OIL_ULTRAMARINE_D
#define REMBRANDT_OIL_ULTRAMARINE_D vec3(0.118, 0.114, 0.627)
#endif
#ifndef ULTRAMARINE_D
#define ULTRAMARINE_D REMBRANDT_OIL_ULTRAMARINE_D
#endif

#ifndef REMBRANDT_OIL_ULTRAMARINE_VIOLET
#define REMBRANDT_OIL_ULTRAMARINE_VIOLET vec3(0.306, 0.263, 0.584)
#endif
#ifndef ULTRAMARINE_VIOLET
#define ULTRAMARINE_VIOLET REMBRANDT_OIL_ULTRAMARINE_VIOLET
#endif

#ifndef REMBRANDT_OIL_PRUSSIAN_BLUE
#define REMBRANDT_OIL_PRUSSIAN_BLUE vec3(0.094, 0.110, 0.169)
#endif
#ifndef PRUSSIAN_BLUE
#define PRUSSIAN_BLUE REMBRANDT_OIL_PRUSSIAN_BLUE
#endif

#ifndef REMBRANDT_OIL_COBALT_BLUE_D
#define REMBRANDT_OIL_COBALT_BLUE_D vec3(0.094, 0.157, 0.392)
#endif
#ifndef COBALT_BLUE_D
#define COBALT_BLUE_D REMBRANDT_OIL_COBALT_BLUE_D
#endif

#ifndef REMBRANDT_OIL_CERULEAN_BLUE
#define REMBRANDT_OIL_CERULEAN_BLUE vec3(0.000, 0.475, 0.761)
#endif
#ifndef CERULEAN_BLUE
#define CERULEAN_BLUE REMBRANDT_OIL_CERULEAN_BLUE
#endif

#ifndef REMBRANDT_OIL_PERM.VIOLET_M
#define REMBRANDT_OIL_PERM.VIOLET_M vec3(0.388, 0.000, 0.212)
#endif
#ifndef PERM.VIOLET_M
#define PERM.VIOLET_M REMBRANDT_OIL_PERM.VIOLET_M
#endif

#ifndef REMBRANDT_OIL_COBALT_VIOLET
#define REMBRANDT_OIL_COBALT_VIOLET vec3(0.518, 0.239, 0.435)
#endif
#ifndef COBALT_VIOLET
#define COBALT_VIOLET REMBRANDT_OIL_COBALT_VIOLET
#endif

#ifndef REMBRANDT_OIL_PERM._BLUE_VIOLET
#define REMBRANDT_OIL_PERM._BLUE_VIOLET vec3(0.341, 0.094, 0.447)
#endif
#ifndef PERM._BLUE_VIOLET
#define PERM._BLUE_VIOLET REMBRANDT_OIL_PERM._BLUE_VIOLET
#endif

#ifndef REMBRANDT_OIL_PHTHALO_BLUEGREEN
#define REMBRANDT_OIL_PHTHALO_BLUEGREEN vec3(0.114, 0.086, 0.220)
#endif
#ifndef PHTHALO_BLUEGREEN
#define PHTHALO_BLUEGREEN REMBRANDT_OIL_PHTHALO_BLUEGREEN
#endif

#ifndef REMBRANDT_OIL_PHTHALO_BLUE_RED
#define REMBRANDT_OIL_PHTHALO_BLUE_RED vec3(0.027, 0.169, 0.451)
#endif
#ifndef PHTHALO_BLUE_RED
#define PHTHALO_BLUE_RED REMBRANDT_OIL_PHTHALO_BLUE_RED
#endif

#ifndef REMBRANDT_OIL_INDANTHRENE_BLUE
#define REMBRANDT_OIL_INDANTHRENE_BLUE vec3(0.118, 0.125, 0.184)
#endif
#ifndef INDANTHRENE_BLUE
#define INDANTHRENE_BLUE REMBRANDT_OIL_INDANTHRENE_BLUE
#endif

#ifndef REMBRANDT_OIL_COBALT_TURQ.BLUE
#define REMBRANDT_OIL_COBALT_TURQ.BLUE vec3(0.000, 0.376, 0.494)
#endif
#ifndef COBALT_TURQ.BLUE
#define COBALT_TURQ.BLUE REMBRANDT_OIL_COBALT_TURQ.BLUE
#endif

#ifndef REMBRANDT_OIL_COBALT_GREEN
#define REMBRANDT_OIL_COBALT_GREEN vec3(0.000, 0.408, 0.353)
#endif
#ifndef COBALT_GREEN
#define COBALT_GREEN REMBRANDT_OIL_COBALT_GREEN
#endif

#ifndef REMBRANDT_OIL_VIRIDIAN
#define REMBRANDT_OIL_VIRIDIAN vec3(0.000, 0.349, 0.333)
#endif
#ifndef VIRIDIAN
#define VIRIDIAN REMBRANDT_OIL_VIRIDIAN
#endif

#ifndef REMBRANDT_OIL_SAP_GREEN
#define REMBRANDT_OIL_SAP_GREEN vec3(0.286, 0.388, 0.239)
#endif
#ifndef SAP_GREEN
#define SAP_GREEN REMBRANDT_OIL_SAP_GREEN
#endif

#ifndef REMBRANDT_OIL_CHROMIUM_OX.GREEN
#define REMBRANDT_OIL_CHROMIUM_OX.GREEN vec3(0.271, 0.416, 0.259)
#endif
#ifndef CHROMIUM_OX.GREEN
#define CHROMIUM_OX.GREEN REMBRANDT_OIL_CHROMIUM_OX.GREEN
#endif

#ifndef REMBRANDT_OIL_PHTHALO_GREENBLUE
#define REMBRANDT_OIL_PHTHALO_GREENBLUE vec3(0.000, 0.263, 0.204)
#endif
#ifndef PHTHALO_GREENBLUE
#define PHTHALO_GREENBLUE REMBRANDT_OIL_PHTHALO_GREENBLUE
#endif

#ifndef REMBRANDT_OIL_PHTHALO_GREEN_YELLOW
#define REMBRANDT_OIL_PHTHALO_GREEN_YELLOW vec3(0.000, 0.322, 0.157)
#endif
#ifndef PHTHALO_GREEN_YELLOW
#define PHTHALO_GREEN_YELLOW REMBRANDT_OIL_PHTHALO_GREEN_YELLOW
#endif

#ifndef REMBRANDT_OIL_COBALT_TURQ.GREEN
#define REMBRANDT_OIL_COBALT_TURQ.GREEN vec3(0.137, 0.490, 0.337)
#endif
#ifndef COBALT_TURQ.GREEN
#define COBALT_TURQ.GREEN REMBRANDT_OIL_COBALT_TURQ.GREEN
#endif

#ifndef REMBRANDT_OIL_IVORY_BLACK
#define REMBRANDT_OIL_IVORY_BLACK vec3(0.192, 0.200, 0.212)
#endif
#ifndef IVORY_BLACK
#define IVORY_BLACK REMBRANDT_OIL_IVORY_BLACK
#endif

