#include "math/abs.cuh"
#include "math/adaptiveThreshold.cuh"
#include "math/asin.cuh"
#include "math/bump.cuh"
#include "math/clamp.cuh"
#include "math/const.cuh"
#include "math/cross.cuh"
#include "math/cubic.cuh"
#include "math/decimate.cuh"
#include "math/dot.cuh"
#include "math/floor.cuh"
#include "math/frac.cuh"
#include "math/fract.cuh"
#include "math/gain.cuh"
#include "math/gaussian.cuh"
#include "math/grad4.cuh"
#include "math/greaterThan.cuh"
#include "math/highPass.cuh"
#include "math/invCubic.cuh"
#include "math/invQuartic.cuh"
// #include "math/inverse.cuh"
#include "math/length.cuh"
#include "math/lengthSq.cuh"
#include "math/lerp.cuh"
#include "math/map.cuh"
#include "math/max.cuh"
#include "math/min.cuh"
#include "math/mirror.cuh"
#include "math/mix.cuh"
#include "math/mmax.cuh"
#include "math/mmin.cuh"
#include "math/mod.cuh"
#include "math/mod289.cuh"
#include "math/normalize.cuh"
#include "math/operations.cuh"
#include "math/parabola.cuh"
#include "math/permute.cuh"
#include "math/pow.cuh"
#include "math/pow2.cuh"
#include "math/pow3.cuh"
#include "math/pow5.cuh"
#include "math/pow7.cuh"
#include "math/powFast.cuh"
#include "math/quartic.cuh"
#include "math/reflect.cuh"
// #include "math/rotate2d.cuh"
// #include "math/rotate3d.cuh"
// #include "math/rotate4d.cuh"
// #include "math/rotate4dX.cuh"
// #include "math/rotate4dY.cuh"
// #include "math/rotate4dZ.cuh"
#include "math/saturate.cuh"
#include "math/saturateMediump.cuh"
#include "math/sign.cuh"
#include "math/sin.cuh"
#include "math/smootherstep.cuh"
#include "math/smoothstep.cuh"
#include "math/sqrt.cuh"
#include "math/step.cuh"
#include "math/taylorInvSqrt.cuh"
#include "math/unpack.cuh"
#include "math/within.cuh"