/*
contributors: Patricio Gonzalez Vivo
description: "RGB colors from Gamblin's oil paint colors. \nBased on https://sensuallogic.com/artistcolordata\n"
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/color_pigments.frag
license:
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Prosperity License - https://prosperitylicense.com/versions/3.0.0
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Patron License - https://lygia.xyz/license
*/

#ifndef GAMBLIN_OIL_ULTRAMARINE_BLUE
#define GAMBLIN_OIL_ULTRAMARINE_BLUE float3(0.173, 0.173, 0.231)
#endif
#ifndef ULTRAMARINE_BLUE
#define ULTRAMARINE_BLUE GAMBLIN_OIL_ULTRAMARINE_BLUE
#endif

#ifndef GAMBLIN_OIL_CADMIUM_LEMON
#define GAMBLIN_OIL_CADMIUM_LEMON float3(0.992, 0.867, 0.000)
#endif
#ifndef CADMIUM_LEMON
#define CADMIUM_LEMON GAMBLIN_OIL_CADMIUM_LEMON
#endif

#ifndef GAMBLIN_OIL_CADMIUM_RED
#define GAMBLIN_OIL_CADMIUM_RED float3(0.776, 0.208, 0.227)
#endif
#ifndef CADMIUM_RED
#define CADMIUM_RED GAMBLIN_OIL_CADMIUM_RED
#endif

#ifndef GAMBLIN_OIL_IVORY_BLACK
#define GAMBLIN_OIL_IVORY_BLACK float3(0.180, 0.180, 0.180)
#endif
#ifndef IVORY_BLACK
#define IVORY_BLACK GAMBLIN_OIL_IVORY_BLACK
#endif

#ifndef GAMBLIN_OIL_MARS_BLACK
#define GAMBLIN_OIL_MARS_BLACK float3(0.125, 0.118, 0.118)
#endif
#ifndef MARS_BLACK
#define MARS_BLACK GAMBLIN_OIL_MARS_BLACK
#endif

#ifndef GAMBLIN_OIL_BURNT_UMBER
#define GAMBLIN_OIL_BURNT_UMBER float3(0.208, 0.141, 0.118)
#endif
#ifndef BURNT_UMBER
#define BURNT_UMBER GAMBLIN_OIL_BURNT_UMBER
#endif

#ifndef GAMBLIN_OIL_RAW_UMBER
#define GAMBLIN_OIL_RAW_UMBER float3(0.259, 0.227, 0.200)
#endif
#ifndef RAW_UMBER
#define RAW_UMBER GAMBLIN_OIL_RAW_UMBER
#endif

#ifndef GAMBLIN_OIL_BURNT_SIENNA
#define GAMBLIN_OIL_BURNT_SIENNA float3(0.400, 0.243, 0.212)
#endif
#ifndef BURNT_SIENNA
#define BURNT_SIENNA GAMBLIN_OIL_BURNT_SIENNA
#endif

#ifndef GAMBLIN_OIL_RAW_SIENNA
#define GAMBLIN_OIL_RAW_SIENNA float3(0.584, 0.357, 0.165)
#endif
#ifndef RAW_SIENNA
#define RAW_SIENNA GAMBLIN_OIL_RAW_SIENNA
#endif

#ifndef GAMBLIN_OIL_YELLOW_OCHRE
#define GAMBLIN_OIL_YELLOW_OCHRE float3(0.706, 0.486, 0.188)
#endif
#ifndef YELLOW_OCHRE
#define YELLOW_OCHRE GAMBLIN_OIL_YELLOW_OCHRE
#endif

#ifndef GAMBLIN_OIL_INDIAN_RED
#define GAMBLIN_OIL_INDIAN_RED float3(0.431, 0.176, 0.157)
#endif
#ifndef INDIAN_RED
#define INDIAN_RED GAMBLIN_OIL_INDIAN_RED
#endif

#ifndef GAMBLIN_OIL_EMERALD_GREEN
#define GAMBLIN_OIL_EMERALD_GREEN float3(0.000, 0.533, 0.282)
#endif
#ifndef EMERALD_GREEN
#define EMERALD_GREEN GAMBLIN_OIL_EMERALD_GREEN
#endif

#ifndef GAMBLIN_OIL_VIRIDIAN
#define GAMBLIN_OIL_VIRIDIAN float3(0.094, 0.282, 0.243)
#endif
#ifndef VIRIDIAN
#define VIRIDIAN GAMBLIN_OIL_VIRIDIAN
#endif

#ifndef GAMBLIN_OIL_COBALT_GREEN
#define GAMBLIN_OIL_COBALT_GREEN float3(0.043, 0.294, 0.235)
#endif
#ifndef COBALT_GREEN
#define COBALT_GREEN GAMBLIN_OIL_COBALT_GREEN
#endif

#ifndef GAMBLIN_OIL_PHTHALO_TURQUOISE
#define GAMBLIN_OIL_PHTHALO_TURQUOISE float3(0.024, 0.102, 0.145)
#endif
#ifndef PHTHALO_TURQUOISE
#define PHTHALO_TURQUOISE GAMBLIN_OIL_PHTHALO_TURQUOISE
#endif

#ifndef GAMBLIN_OIL_COBALT_TEAL
#define GAMBLIN_OIL_COBALT_TEAL float3(0.016, 0.718, 0.706)
#endif
#ifndef COBALT_TEAL
#define COBALT_TEAL GAMBLIN_OIL_COBALT_TEAL
#endif

#ifndef GAMBLIN_OIL_MANGANESE_BLUE
#define GAMBLIN_OIL_MANGANESE_BLUE float3(0.102, 0.290, 0.384)
#endif
#ifndef MANGANESE_BLUE
#define MANGANESE_BLUE GAMBLIN_OIL_MANGANESE_BLUE
#endif

#ifndef GAMBLIN_OIL_CERULEAN_BLUE
#define GAMBLIN_OIL_CERULEAN_BLUE float3(0.000, 0.380, 0.549)
#endif
#ifndef CERULEAN_BLUE
#define CERULEAN_BLUE GAMBLIN_OIL_CERULEAN_BLUE
#endif

#ifndef GAMBLIN_OIL_COBALT_BLUE
#define GAMBLIN_OIL_COBALT_BLUE float3(0.000, 0.176, 0.427)
#endif
#ifndef COBALT_BLUE
#define COBALT_BLUE GAMBLIN_OIL_COBALT_BLUE
#endif

#ifndef GAMBLIN_OIL_PHTHALO_BLUE
#define GAMBLIN_OIL_PHTHALO_BLUE float3(0.067, 0.051, 0.141)
#endif
#ifndef PHTHALO_BLUE
#define PHTHALO_BLUE GAMBLIN_OIL_PHTHALO_BLUE
#endif

#ifndef GAMBLIN_OIL_INDANTHRONE_BLUE
#define GAMBLIN_OIL_INDANTHRONE_BLUE float3(0.196, 0.180, 0.204)
#endif
#ifndef INDANTHRONE_BLUE
#define INDANTHRONE_BLUE GAMBLIN_OIL_INDANTHRONE_BLUE
#endif

#ifndef GAMBLIN_OIL_PRUSSIAN_BLUE
#define GAMBLIN_OIL_PRUSSIAN_BLUE float3(0.051, 0.043, 0.047)
#endif
#ifndef PRUSSIAN_BLUE
#define PRUSSIAN_BLUE GAMBLIN_OIL_PRUSSIAN_BLUE
#endif

#ifndef GAMBLIN_OIL_MANGANESE_VIOLET
#define GAMBLIN_OIL_MANGANESE_VIOLET float3(0.235, 0.059, 0.220)
#endif
#ifndef MANGANESE_VIOLET
#define MANGANESE_VIOLET GAMBLIN_OIL_MANGANESE_VIOLET
#endif

#ifndef GAMBLIN_OIL_DIOXAZINE_PURPLE
#define GAMBLIN_OIL_DIOXAZINE_PURPLE float3(0.149, 0.125, 0.129)
#endif
#ifndef DIOXAZINE_PURPLE
#define DIOXAZINE_PURPLE GAMBLIN_OIL_DIOXAZINE_PURPLE
#endif

#ifndef GAMBLIN_OIL_COBALT_VIOLET
#define GAMBLIN_OIL_COBALT_VIOLET float3(0.275, 0.106, 0.282)
#endif
#ifndef COBALT_VIOLET
#define COBALT_VIOLET GAMBLIN_OIL_COBALT_VIOLET
#endif

#ifndef GAMBLIN_OIL_QUINACRIDONE_VIOLET
#define GAMBLIN_OIL_QUINACRIDONE_VIOLET float3(0.333, 0.078, 0.133)
#endif
#ifndef QUINACRIDONE_VIOLET
#define QUINACRIDONE_VIOLET GAMBLIN_OIL_QUINACRIDONE_VIOLET
#endif

#ifndef GAMBLIN_OIL_QUINACRIDONE_MAGENTA
#define GAMBLIN_OIL_QUINACRIDONE_MAGENTA float3(0.380, 0.071, 0.161)
#endif
#ifndef QUINACRIDONE_MAGENTA
#define QUINACRIDONE_MAGENTA GAMBLIN_OIL_QUINACRIDONE_MAGENTA
#endif

#ifndef GAMBLIN_OIL_PHTHALO_EMERALD
#define GAMBLIN_OIL_PHTHALO_EMERALD float3(0.000, 0.141, 0.114)
#endif
#ifndef PHTHALO_EMERALD
#define PHTHALO_EMERALD GAMBLIN_OIL_PHTHALO_EMERALD
#endif

#ifndef GAMBLIN_OIL_CHROMIUM_OXIDE_GREEN
#define GAMBLIN_OIL_CHROMIUM_OXIDE_GREEN float3(0.298, 0.427, 0.286)
#endif
#ifndef CHROMIUM_OXIDE_GREEN
#define CHROMIUM_OXIDE_GREEN GAMBLIN_OIL_CHROMIUM_OXIDE_GREEN
#endif

#ifndef GAMBLIN_OIL_CADMIUM_YELLOW_DEEP
#define GAMBLIN_OIL_CADMIUM_YELLOW_DEEP float3(1.000, 0.647, 0.000)
#endif
#ifndef CADMIUM_YELLOW_DEEP
#define CADMIUM_YELLOW_DEEP GAMBLIN_OIL_CADMIUM_YELLOW_DEEP
#endif

#ifndef GAMBLIN_OIL_PERMANENT_GREEN_LIGHT
#define GAMBLIN_OIL_PERMANENT_GREEN_LIGHT float3(0.137, 0.588, 0.000)
#endif
#ifndef PERMANENT_GREEN_LIGHT
#define PERMANENT_GREEN_LIGHT GAMBLIN_OIL_PERMANENT_GREEN_LIGHT
#endif

#ifndef GAMBLIN_OIL_CADMIUM_YELLOW
#define GAMBLIN_OIL_CADMIUM_YELLOW float3(1.000, 0.722, 0.000)
#endif
#ifndef CADMIUM_YELLOW
#define CADMIUM_YELLOW GAMBLIN_OIL_CADMIUM_YELLOW
#endif

#ifndef GAMBLIN_OIL_CADMIUM_YELLOW_LIGHT
#define GAMBLIN_OIL_CADMIUM_YELLOW_LIGHT float3(0.996, 0.851, 0.000)
#endif
#ifndef CADMIUM_YELLOW_LIGHT
#define CADMIUM_YELLOW_LIGHT GAMBLIN_OIL_CADMIUM_YELLOW_LIGHT
#endif

#ifndef GAMBLIN_OIL_HANSA_YELLOW_LIGHT
#define GAMBLIN_OIL_HANSA_YELLOW_LIGHT float3(0.945, 0.796, 0.000)
#endif
#ifndef HANSA_YELLOW_LIGHT
#define HANSA_YELLOW_LIGHT GAMBLIN_OIL_HANSA_YELLOW_LIGHT
#endif

#ifndef GAMBLIN_OIL_CADMIUM_ORANGE
#define GAMBLIN_OIL_CADMIUM_ORANGE float3(1.000, 0.494, 0.000)
#endif
#ifndef CADMIUM_ORANGE
#define CADMIUM_ORANGE GAMBLIN_OIL_CADMIUM_ORANGE
#endif

#ifndef GAMBLIN_OIL_CADMIUM_ORANGE_DEEP
#define GAMBLIN_OIL_CADMIUM_ORANGE_DEEP float3(0.953, 0.357, 0.090)
#endif
#ifndef CADMIUM_ORANGE_DEEP
#define CADMIUM_ORANGE_DEEP GAMBLIN_OIL_CADMIUM_ORANGE_DEEP
#endif

#ifndef GAMBLIN_OIL_CADMIUM_RED_LIGHT
#define GAMBLIN_OIL_CADMIUM_RED_LIGHT float3(0.863, 0.196, 0.157)
#endif
#ifndef CADMIUM_RED_LIGHT
#define CADMIUM_RED_LIGHT GAMBLIN_OIL_CADMIUM_RED_LIGHT
#endif

#ifndef GAMBLIN_OIL_NAPTHOL_SCARLET
#define GAMBLIN_OIL_NAPTHOL_SCARLET float3(0.749, 0.157, 0.102)
#endif
#ifndef NAPTHOL_SCARLET
#define NAPTHOL_SCARLET GAMBLIN_OIL_NAPTHOL_SCARLET
#endif

#ifndef GAMBLIN_OIL_PERYLENE_RED
#define GAMBLIN_OIL_PERYLENE_RED float3(0.388, 0.000, 0.027)
#endif
#ifndef PERYLENE_RED
#define PERYLENE_RED GAMBLIN_OIL_PERYLENE_RED
#endif

#ifndef GAMBLIN_OIL_CADMIUM_RED_DEEP
#define GAMBLIN_OIL_CADMIUM_RED_DEEP float3(0.647, 0.176, 0.220)
#endif
#ifndef CADMIUM_RED_DEEP
#define CADMIUM_RED_DEEP GAMBLIN_OIL_CADMIUM_RED_DEEP
#endif

#ifndef GAMBLIN_OIL_QUINACRIDONE_RED
#define GAMBLIN_OIL_QUINACRIDONE_RED float3(0.541, 0.098, 0.165)
#endif
#ifndef QUINACRIDONE_RED
#define QUINACRIDONE_RED GAMBLIN_OIL_QUINACRIDONE_RED
#endif

#ifndef GAMBLIN_OIL_ALIZARIN_CRIMSON
#define GAMBLIN_OIL_ALIZARIN_CRIMSON float3(0.282, 0.110, 0.122)
#endif
#ifndef ALIZARIN_CRIMSON
#define ALIZARIN_CRIMSON GAMBLIN_OIL_ALIZARIN_CRIMSON
#endif

#ifndef GAMBLIN_OIL_NAPHTOL_RED
#define GAMBLIN_OIL_NAPHTOL_RED float3(0.749, 0.012, 0.000)
#endif
#ifndef NAPHTOL_RED
#define NAPHTOL_RED GAMBLIN_OIL_NAPHTOL_RED
#endif

#ifndef GAMBLIN_OIL_TITANIUM_WHITE
#define GAMBLIN_OIL_TITANIUM_WHITE float3(0.973, 0.961, 0.929)
#endif
#ifndef TITANIUM_WHITE
#define TITANIUM_WHITE GAMBLIN_OIL_TITANIUM_WHITE
#endif

#ifndef GAMBLIN_OIL_TITANIUM_BUFF
#define GAMBLIN_OIL_TITANIUM_BUFF float3(0.796, 0.710, 0.545)
#endif
#ifndef TITANIUM_BUFF
#define TITANIUM_BUFF GAMBLIN_OIL_TITANIUM_BUFF
#endif

