/*
contributors: Patricio Gonzalez Vivo
description: "RGB colors from Golden's acrylic paint colors. \nBased on https://sensuallogic.com/artistcolordata\n"
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/color_pigments.frag
license:
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Prosperity License - https://prosperitylicense.com/versions/3.0.0
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Patron License - https://lygia.xyz/license
*/

#ifndef GOLDEN_ACRYLIC_BONE_BLACK
#define GOLDEN_ACRYLIC_BONE_BLACK vec3(0.137, 0.133, 0.141)
#endif
#ifndef BONE_BLACK
#define BONE_BLACK GOLDEN_ACRYLIC_BONE_BLACK
#endif

#ifndef GOLDEN_ACRYLIC_BURNT_SIENNA
#define GOLDEN_ACRYLIC_BURNT_SIENNA vec3(0.439, 0.243, 0.208)
#endif
#ifndef BURNT_SIENNA
#define BURNT_SIENNA GOLDEN_ACRYLIC_BURNT_SIENNA
#endif

#ifndef GOLDEN_ACRYLIC_BURNT_UMBER
#define GOLDEN_ACRYLIC_BURNT_UMBER vec3(0.275, 0.220, 0.212)
#endif
#ifndef BURNT_UMBER
#define BURNT_UMBER GOLDEN_ACRYLIC_BURNT_UMBER
#endif

#ifndef GOLDEN_ACRYLIC_CARBON_BLACK
#define GOLDEN_ACRYLIC_CARBON_BLACK vec3(0.118, 0.114, 0.122)
#endif
#ifndef CARBON_BLACK
#define CARBON_BLACK GOLDEN_ACRYLIC_CARBON_BLACK
#endif

#ifndef GOLDEN_ACRYLIC_CERULEAN_BLUE_CHROMIUM
#define GOLDEN_ACRYLIC_CERULEAN_BLUE_CHROMIUM vec3(0.000, 0.333, 0.596)
#endif
#ifndef CERULEAN_BLUE_CHROMIUM
#define CERULEAN_BLUE_CHROMIUM GOLDEN_ACRYLIC_CERULEAN_BLUE_CHROMIUM
#endif

#ifndef GOLDEN_ACRYLIC_CHROMIUM_OXIDE_GREEN
#define GOLDEN_ACRYLIC_CHROMIUM_OXIDE_GREEN vec3(0.298, 0.416, 0.263)
#endif
#ifndef CHROMIUM_OXIDE_GREEN
#define CHROMIUM_OXIDE_GREEN GOLDEN_ACRYLIC_CHROMIUM_OXIDE_GREEN
#endif

#ifndef GOLDEN_ACRYLIC_CADMIUM_ORANGE
#define GOLDEN_ACRYLIC_CADMIUM_ORANGE vec3(1.000, 0.388, 0.000)
#endif
#ifndef CADMIUM_ORANGE
#define CADMIUM_ORANGE GOLDEN_ACRYLIC_CADMIUM_ORANGE
#endif

#ifndef GOLDEN_ACRYLIC_CADMIUM_RED_LIGHT
#define GOLDEN_ACRYLIC_CADMIUM_RED_LIGHT vec3(0.890, 0.157, 0.063)
#endif
#ifndef CADMIUM_RED_LIGHT
#define CADMIUM_RED_LIGHT GOLDEN_ACRYLIC_CADMIUM_RED_LIGHT
#endif

#ifndef GOLDEN_ACRYLIC_CADMIUM_RED
#define GOLDEN_ACRYLIC_CADMIUM_RED vec3(0.725, 0.020, 0.125)
#endif
#ifndef CADMIUM_RED
#define CADMIUM_RED GOLDEN_ACRYLIC_CADMIUM_RED
#endif

#ifndef GOLDEN_ACRYLIC_CADMIUM_YELLOW
#define GOLDEN_ACRYLIC_CADMIUM_YELLOW vec3(1.000, 0.784, 0.000)
#endif
#ifndef CADMIUM_YELLOW
#define CADMIUM_YELLOW GOLDEN_ACRYLIC_CADMIUM_YELLOW
#endif

#ifndef GOLDEN_ACRYLIC_CADMIUM_YELLOW_PRIMROSE
#define GOLDEN_ACRYLIC_CADMIUM_YELLOW_PRIMROSE vec3(0.976, 0.906, 0.078)
#endif
#ifndef CADMIUM_YELLOW_PRIMROSE
#define CADMIUM_YELLOW_PRIMROSE GOLDEN_ACRYLIC_CADMIUM_YELLOW_PRIMROSE
#endif

#ifndef GOLDEN_ACRYLIC_COBALT_BLUE
#define GOLDEN_ACRYLIC_COBALT_BLUE vec3(0.031, 0.196, 0.627)
#endif
#ifndef COBALT_BLUE
#define COBALT_BLUE GOLDEN_ACRYLIC_COBALT_BLUE
#endif

#ifndef GOLDEN_ACRYLIC_DIARYLIDE_YELLOW
#define GOLDEN_ACRYLIC_DIARYLIDE_YELLOW vec3(1.000, 0.635, 0.000)
#endif
#ifndef DIARYLIDE_YELLOW
#define DIARYLIDE_YELLOW GOLDEN_ACRYLIC_DIARYLIDE_YELLOW
#endif

#ifndef GOLDEN_ACRYLIC_DIOXAZINE_PURPLE
#define GOLDEN_ACRYLIC_DIOXAZINE_PURPLE vec3(0.098, 0.067, 0.075)
#endif
#ifndef DIOXAZINE_PURPLE
#define DIOXAZINE_PURPLE GOLDEN_ACRYLIC_DIOXAZINE_PURPLE
#endif

#ifndef GOLDEN_ACRYLIC_HANSA_YELLOW_LIGHT
#define GOLDEN_ACRYLIC_HANSA_YELLOW_LIGHT vec3(0.980, 0.886, 0.000)
#endif
#ifndef HANSA_YELLOW_LIGHT
#define HANSA_YELLOW_LIGHT GOLDEN_ACRYLIC_HANSA_YELLOW_LIGHT
#endif

#ifndef GOLDEN_ACRYLIC_NICKEL_AZO_YELLOW
#define GOLDEN_ACRYLIC_NICKEL_AZO_YELLOW vec3(0.494, 0.365, 0.035)
#endif
#ifndef NICKEL_AZO_YELLOW
#define NICKEL_AZO_YELLOW GOLDEN_ACRYLIC_NICKEL_AZO_YELLOW
#endif

#ifndef GOLDEN_ACRYLIC_PHTHALO_BLUE
#define GOLDEN_ACRYLIC_PHTHALO_BLUE vec3(0.063, 0.012, 0.243)
#endif
#ifndef PHTHALO_BLUE
#define PHTHALO_BLUE GOLDEN_ACRYLIC_PHTHALO_BLUE
#endif

#ifndef GOLDEN_ACRYLIC_PHTHALO_GREEN
#define GOLDEN_ACRYLIC_PHTHALO_GREEN vec3(0.000, 0.122, 0.161)
#endif
#ifndef PHTHALO_GREEN
#define PHTHALO_GREEN GOLDEN_ACRYLIC_PHTHALO_GREEN
#endif

#ifndef GOLDEN_ACRYLIC_PYRROLE_ORANGE
#define GOLDEN_ACRYLIC_PYRROLE_ORANGE vec3(0.937, 0.239, 0.000)
#endif
#ifndef PYRROLE_ORANGE
#define PYRROLE_ORANGE GOLDEN_ACRYLIC_PYRROLE_ORANGE
#endif

#ifndef GOLDEN_ACRYLIC_PYRROLE_RED
#define GOLDEN_ACRYLIC_PYRROLE_RED vec3(0.733, 0.000, 0.000)
#endif
#ifndef PYRROLE_RED
#define PYRROLE_RED GOLDEN_ACRYLIC_PYRROLE_RED
#endif

#ifndef GOLDEN_ACRYLIC_QUINACRIDONE_MAGENTA
#define GOLDEN_ACRYLIC_QUINACRIDONE_MAGENTA vec3(0.353, 0.000, 0.145)
#endif
#ifndef QUINACRIDONE_MAGENTA
#define QUINACRIDONE_MAGENTA GOLDEN_ACRYLIC_QUINACRIDONE_MAGENTA
#endif

#ifndef GOLDEN_ACRYLIC_QUINACRIDONE_RED
#define GOLDEN_ACRYLIC_QUINACRIDONE_RED vec3(0.588, 0.000, 0.145)
#endif
#ifndef QUINACRIDONE_RED
#define QUINACRIDONE_RED GOLDEN_ACRYLIC_QUINACRIDONE_RED
#endif

#ifndef GOLDEN_ACRYLIC_RAW_SIENNA
#define GOLDEN_ACRYLIC_RAW_SIENNA vec3(0.616, 0.404, 0.204)
#endif
#ifndef RAW_SIENNA
#define RAW_SIENNA GOLDEN_ACRYLIC_RAW_SIENNA
#endif

#ifndef GOLDEN_ACRYLIC_RAW_UMBER
#define GOLDEN_ACRYLIC_RAW_UMBER vec3(0.251, 0.220, 0.212)
#endif
#ifndef RAW_UMBER
#define RAW_UMBER GOLDEN_ACRYLIC_RAW_UMBER
#endif

#ifndef GOLDEN_ACRYLIC_RED_OXIDE
#define GOLDEN_ACRYLIC_RED_OXIDE vec3(0.518, 0.208, 0.161)
#endif
#ifndef RED_OXIDE
#define RED_OXIDE GOLDEN_ACRYLIC_RED_OXIDE
#endif

#ifndef GOLDEN_ACRYLIC_TITAN_BUFF
#define GOLDEN_ACRYLIC_TITAN_BUFF vec3(0.882, 0.804, 0.729)
#endif
#ifndef TITAN_BUFF
#define TITAN_BUFF GOLDEN_ACRYLIC_TITAN_BUFF
#endif

#ifndef GOLDEN_ACRYLIC_TITANIUM_WHITE
#define GOLDEN_ACRYLIC_TITANIUM_WHITE vec3(1.000, 0.969, 1.000)
#endif
#ifndef TITANIUM_WHITE
#define TITANIUM_WHITE GOLDEN_ACRYLIC_TITANIUM_WHITE
#endif

#ifndef GOLDEN_ACRYLIC_ULTRAMARINE_BLUE
#define GOLDEN_ACRYLIC_ULTRAMARINE_BLUE vec3(0.196, 0.184, 0.294)
#endif
#ifndef ULTRAMARINE_BLUE
#define ULTRAMARINE_BLUE GOLDEN_ACRYLIC_ULTRAMARINE_BLUE
#endif

#ifndef GOLDEN_ACRYLIC_ULTRAMARINE_VIOLET
#define GOLDEN_ACRYLIC_ULTRAMARINE_VIOLET vec3(0.212, 0.184, 0.294)
#endif
#ifndef ULTRAMARINE_VIOLET
#define ULTRAMARINE_VIOLET GOLDEN_ACRYLIC_ULTRAMARINE_VIOLET
#endif

#ifndef GOLDEN_ACRYLIC_YELLOW_OCHRE
#define GOLDEN_ACRYLIC_YELLOW_OCHRE vec3(0.729, 0.486, 0.200)
#endif
#ifndef YELLOW_OCHRE
#define YELLOW_OCHRE GOLDEN_ACRYLIC_YELLOW_OCHRE
#endif

#ifndef GOLDEN_ACRYLIC_NATURAL_GRAY
#define GOLDEN_ACRYLIC_NATURAL_GRAY vec3(0.471, 0.455, 0.478)
#endif
#ifndef NATURAL_GRAY
#define NATURAL_GRAY GOLDEN_ACRYLIC_NATURAL_GRAY
#endif

#ifndef GOLDEN_ACRYLIC_PRIMARY_CYAN
#define GOLDEN_ACRYLIC_PRIMARY_CYAN vec3(0.000, 0.247, 0.510)
#endif
#ifndef PRIMARY_CYAN
#define PRIMARY_CYAN GOLDEN_ACRYLIC_PRIMARY_CYAN
#endif

#ifndef GOLDEN_ACRYLIC_PRIMARY_MAGENTA
#define GOLDEN_ACRYLIC_PRIMARY_MAGENTA vec3(0.663, 0.102, 0.192)
#endif
#ifndef PRIMARY_MAGENTA
#define PRIMARY_MAGENTA GOLDEN_ACRYLIC_PRIMARY_MAGENTA
#endif

#ifndef GOLDEN_ACRYLIC_PRIMARY_YELLOW
#define GOLDEN_ACRYLIC_PRIMARY_YELLOW vec3(1.000, 0.843, 0.000)
#endif
#ifndef PRIMARY_YELLOW
#define PRIMARY_YELLOW GOLDEN_ACRYLIC_PRIMARY_YELLOW
#endif

