/*
contributors: Patricio Gonzalez Vivo
description: "RGB colors from Liquitex's acrylic paint colors. \nBased on https://sensuallogic.com/artistcolordata\n"
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/color_pigments.frag
license:
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Prosperity License - https://prosperitylicense.com/versions/3.0.0
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Patron License - https://lygia.xyz/license
*/

#ifndef LIQUITEX_ACRYLIC_QUINACRIDONE_BLUE_VIOLET
#define LIQUITEX_ACRYLIC_QUINACRIDONE_BLUE_VIOLET vec3(0.180, 0.071, 0.118)
#endif
#ifndef QUINACRIDONE_BLUE_VIOLET
#define QUINACRIDONE_BLUE_VIOLET LIQUITEX_ACRYLIC_QUINACRIDONE_BLUE_VIOLET
#endif

#ifndef LIQUITEX_ACRYLIC_BURNT_SIENNA
#define LIQUITEX_ACRYLIC_BURNT_SIENNA vec3(0.451, 0.251, 0.224)
#endif
#ifndef BURNT_SIENNA
#define BURNT_SIENNA LIQUITEX_ACRYLIC_BURNT_SIENNA
#endif

#ifndef LIQUITEX_ACRYLIC_CADMIUM_ORANGE
#define LIQUITEX_ACRYLIC_CADMIUM_ORANGE vec3(1.000, 0.475, 0.000)
#endif
#ifndef CADMIUM_ORANGE
#define CADMIUM_ORANGE LIQUITEX_ACRYLIC_CADMIUM_ORANGE
#endif

#ifndef LIQUITEX_ACRYLIC_CADMIUM_RED
#define LIQUITEX_ACRYLIC_CADMIUM_RED vec3(0.886, 0.204, 0.110)
#endif
#ifndef CADMIUM_RED
#define CADMIUM_RED LIQUITEX_ACRYLIC_CADMIUM_RED
#endif

#ifndef LIQUITEX_ACRYLIC_CADMIUM_YELLOW_DEEP
#define LIQUITEX_ACRYLIC_CADMIUM_YELLOW_DEEP vec3(1.000, 0.671, 0.000)
#endif
#ifndef CADMIUM_YELLOW_DEEP
#define CADMIUM_YELLOW_DEEP LIQUITEX_ACRYLIC_CADMIUM_YELLOW_DEEP
#endif

#ifndef LIQUITEX_ACRYLIC_CERULEAN_BLUE
#define LIQUITEX_ACRYLIC_CERULEAN_BLUE vec3(0.000, 0.376, 0.631)
#endif
#ifndef CERULEAN_BLUE
#define CERULEAN_BLUE LIQUITEX_ACRYLIC_CERULEAN_BLUE
#endif

#ifndef LIQUITEX_ACRYLIC_COBALT_TEAL
#define LIQUITEX_ACRYLIC_COBALT_TEAL vec3(0.000, 0.663, 0.694)
#endif
#ifndef COBALT_TEAL
#define COBALT_TEAL LIQUITEX_ACRYLIC_COBALT_TEAL
#endif

#ifndef LIQUITEX_ACRYLIC_IVORY_BLACK
#define LIQUITEX_ACRYLIC_IVORY_BLACK vec3(0.173, 0.169, 0.184)
#endif
#ifndef IVORY_BLACK
#define IVORY_BLACK LIQUITEX_ACRYLIC_IVORY_BLACK
#endif

#ifndef LIQUITEX_ACRYLIC_NAPHTHOL
#define LIQUITEX_ACRYLIC_NAPHTHOL vec3(0.671, 0.000, 0.125)
#endif
#ifndef NAPHTHOL
#define NAPHTHOL LIQUITEX_ACRYLIC_NAPHTHOL
#endif

#ifndef LIQUITEX_ACRYLIC_DEEP_MAGENTA
#define LIQUITEX_ACRYLIC_DEEP_MAGENTA vec3(0.376, 0.067, 0.231)
#endif
#ifndef DEEP_MAGENTA
#define DEEP_MAGENTA LIQUITEX_ACRYLIC_DEEP_MAGENTA
#endif

#ifndef LIQUITEX_ACRYLIC_LIGHT_GREEN_PERMANENT
#define LIQUITEX_ACRYLIC_LIGHT_GREEN_PERMANENT vec3(0.000, 0.557, 0.192)
#endif
#ifndef LIGHT_GREEN_PERMANENT
#define LIGHT_GREEN_PERMANENT LIQUITEX_ACRYLIC_LIGHT_GREEN_PERMANENT
#endif

#ifndef LIQUITEX_ACRYLIC_PHTHALOCYANINE_BLUE
#define LIQUITEX_ACRYLIC_PHTHALOCYANINE_BLUE vec3(0.129, 0.098, 0.251)
#endif
#ifndef PHTHALOCYANINE_BLUE
#define PHTHALOCYANINE_BLUE LIQUITEX_ACRYLIC_PHTHALOCYANINE_BLUE
#endif

#ifndef LIQUITEX_ACRYLIC_PHTHALOCYANINE_GREEN
#define LIQUITEX_ACRYLIC_PHTHALOCYANINE_GREEN vec3(0.000, 0.176, 0.165)
#endif
#ifndef PHTHALOCYANINE_GREEN
#define PHTHALOCYANINE_GREEN LIQUITEX_ACRYLIC_PHTHALOCYANINE_GREEN
#endif

#ifndef LIQUITEX_ACRYLIC_RAW_SIENNA
#define LIQUITEX_ACRYLIC_RAW_SIENNA vec3(0.588, 0.361, 0.224)
#endif
#ifndef RAW_SIENNA
#define RAW_SIENNA LIQUITEX_ACRYLIC_RAW_SIENNA
#endif

#ifndef LIQUITEX_ACRYLIC_COBALT_BLUE
#define LIQUITEX_ACRYLIC_COBALT_BLUE vec3(0.192, 0.227, 0.592)
#endif
#ifndef COBALT_BLUE
#define COBALT_BLUE LIQUITEX_ACRYLIC_COBALT_BLUE
#endif

#ifndef LIQUITEX_ACRYLIC_TITANIUM_WHITE
#define LIQUITEX_ACRYLIC_TITANIUM_WHITE vec3(1.000, 0.976, 1.000)
#endif
#ifndef TITANIUM_WHITE
#define TITANIUM_WHITE LIQUITEX_ACRYLIC_TITANIUM_WHITE
#endif

#ifndef LIQUITEX_ACRYLIC_MEDIUM_MAGENTA
#define LIQUITEX_ACRYLIC_MEDIUM_MAGENTA vec3(0.745, 0.263, 0.596)
#endif
#ifndef MEDIUM_MAGENTA
#define MEDIUM_MAGENTA LIQUITEX_ACRYLIC_MEDIUM_MAGENTA
#endif

#ifndef LIQUITEX_ACRYLIC_NEUTRAL_GRAY
#define LIQUITEX_ACRYLIC_NEUTRAL_GRAY vec3(0.475, 0.467, 0.490)
#endif
#ifndef NEUTRAL_GRAY
#define NEUTRAL_GRAY LIQUITEX_ACRYLIC_NEUTRAL_GRAY
#endif

#ifndef LIQUITEX_ACRYLIC_LIGHT_EMERALD_GREEN
#define LIQUITEX_ACRYLIC_LIGHT_EMERALD_GREEN vec3(0.267, 0.663, 0.290)
#endif
#ifndef LIGHT_EMERALD_GREEN
#define LIGHT_EMERALD_GREEN LIQUITEX_ACRYLIC_LIGHT_EMERALD_GREEN
#endif

#ifndef LIQUITEX_ACRYLIC_VIVID_LIME_GREEN
#define LIQUITEX_ACRYLIC_VIVID_LIME_GREEN vec3(0.514, 0.741, 0.227)
#endif
#ifndef VIVID_LIME_GREEN
#define VIVID_LIME_GREEN LIQUITEX_ACRYLIC_VIVID_LIME_GREEN
#endif

#ifndef LIQUITEX_ACRYLIC_LIGHT_BLUE_PERMANENT
#define LIQUITEX_ACRYLIC_LIGHT_BLUE_PERMANENT vec3(0.239, 0.729, 0.867)
#endif
#ifndef LIGHT_BLUE_PERMANENT
#define LIGHT_BLUE_PERMANENT LIQUITEX_ACRYLIC_LIGHT_BLUE_PERMANENT
#endif

#ifndef LIQUITEX_ACRYLIC_CADMIUM_YELLOW
#define LIQUITEX_ACRYLIC_CADMIUM_YELLOW vec3(1.000, 0.745, 0.000)
#endif
#ifndef CADMIUM_YELLOW
#define CADMIUM_YELLOW LIQUITEX_ACRYLIC_CADMIUM_YELLOW
#endif

