/*
contributors: Patricio Gonzalez Vivo
description: "RGB colors from Winsor & Newton's gouache paint colors. \nBased on https://sensuallogic.com/artistcolordata\n"
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/color_pigments.frag
license:
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Prosperity License - https://prosperitylicense.com/versions/3.0.0
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Patron License - https://lygia.xyz/license
*/

// #define WINDSOR_GOUACHE_ALIZARIN_CRIMSON vec3(0.604, 0.173, 0.263)
// #define ALIZARIN_CRIMSON WINDSOR_GOUACHE_ALIZARIN_CRIMSON

// #define WINDSOR_GOUACHE_BURNT_SIENNA vec3(0.569, 0.298, 0.212)
// #define BURNT_SIENNA WINDSOR_GOUACHE_BURNT_SIENNA

// #define WINDSOR_GOUACHE_BURNT_UMBER vec3(0.408, 0.282, 0.239)
// #define BURNT_UMBER WINDSOR_GOUACHE_BURNT_UMBER

// #define WINDSOR_GOUACHE_CADMIUM_LEMON vec3(1.000, 0.898, 0.180)
// #define CADMIUM_LEMON WINDSOR_GOUACHE_CADMIUM_LEMON

// #define WINDSOR_GOUACHE_CADMIUM_ORANGE vec3(0.992, 0.435, 0.165)
// #define CADMIUM_ORANGE WINDSOR_GOUACHE_CADMIUM_ORANGE

// #define WINDSOR_GOUACHE_CADMIUM_RED vec3(0.824, 0.231, 0.216)
// #define CADMIUM_RED WINDSOR_GOUACHE_CADMIUM_RED

// #define WINDSOR_GOUACHE_CADMIUM_SCARLET vec3(0.914, 0.271, 0.184)
// #define CADMIUM_SCARLET WINDSOR_GOUACHE_CADMIUM_SCARLET

// #define WINDSOR_GOUACHE_CADMIUM_YELLOW vec3(1.000, 0.741, 0.000)
// #define CADMIUM_YELLOW WINDSOR_GOUACHE_CADMIUM_YELLOW

// #define WINDSOR_GOUACHE_CERULEAN_BLUE vec3(0.063, 0.459, 0.655)
// #define CERULEAN_BLUE WINDSOR_GOUACHE_CERULEAN_BLUE

// #define WINDSOR_GOUACHE_COBALT_BLUE vec3(0.129, 0.408, 0.788)
// #define COBALT_BLUE WINDSOR_GOUACHE_COBALT_BLUE

// #define WINDSOR_GOUACHE_COBALT_TURQUOISE_LIGHT vec3(0.000, 0.651, 0.694)
// #define COBALT_TURQUOISE_LIGHT WINDSOR_GOUACHE_COBALT_TURQUOISE_LIGHT

// #define WINDSOR_GOUACHE_FLAME_RED vec3(0.824, 0.251, 0.208)
// #define FLAME_RED WINDSOR_GOUACHE_FLAME_RED

// #define WINDSOR_GOUACHE_INDIGO vec3(0.220, 0.231, 0.345)
// #define INDIGO WINDSOR_GOUACHE_INDIGO

// #define WINDSOR_GOUACHE_IVORY_BLACK vec3(0.173, 0.161, 0.169)
// #define IVORY_BLACK WINDSOR_GOUACHE_IVORY_BLACK

// #define WINDSOR_GOUACHE_JET_BLACK vec3(0.153, 0.129, 0.137)
// #define JET_BLACK WINDSOR_GOUACHE_JET_BLACK

// #define WINDSOR_GOUACHE_LAMP_BLACK vec3(0.224, 0.220, 0.235)
// #define LAMP_BLACK WINDSOR_GOUACHE_LAMP_BLACK

// #define WINDSOR_GOUACHE_LEMON_YELLOW vec3(1.000, 0.918, 0.047)
// #define LEMON_YELLOW WINDSOR_GOUACHE_LEMON_YELLOW

// #define WINDSOR_GOUACHE_LIGHT_PURPLE vec3(0.451, 0.224, 0.596)
// #define LIGHT_PURPLE WINDSOR_GOUACHE_LIGHT_PURPLE

// #define WINDSOR_GOUACHE_MAGENTA vec3(0.467, 0.196, 0.459)
// #define MAGENTA WINDSOR_GOUACHE_MAGENTA

// #define WINDSOR_GOUACHE_MARIGOLD_YELLOW vec3(1.000, 0.471, 0.110)
// #define MARIGOLD_YELLOW WINDSOR_GOUACHE_MARIGOLD_YELLOW

// #define WINDSOR_GOUACHE_NAPLES_YELLOW_DEEP vec3(0.875, 0.604, 0.282)
// #define NAPLES_YELLOW_DEEP WINDSOR_GOUACHE_NAPLES_YELLOW_DEEP

// #define WINDSOR_GOUACHE_ORANGE_LAKE_LIGHT vec3(0.929, 0.376, 0.184)
// #define ORANGE_LAKE_LIGHT WINDSOR_GOUACHE_ORANGE_LAKE_LIGHT

// #define WINDSOR_GOUACHE_OXIDE_OF_CHROMIUM vec3(0.306, 0.420, 0.322)
// #define OXIDE_OF_CHROMIUM WINDSOR_GOUACHE_OXIDE_OF_CHROMIUM

// #define WINDSOR_GOUACHE_PERMANENT_ALIZARIN_CRIMSON vec3(0.612, 0.173, 0.235)
// #define PERMANENT_ALIZARIN_CRIMSON WINDSOR_GOUACHE_PERMANENT_ALIZARIN_CRIMSON

// #define WINDSOR_GOUACHE_PERYLENE_VIOLET vec3(0.298, 0.208, 0.259)
// #define PERYLENE_VIOLET WINDSOR_GOUACHE_PERYLENE_VIOLET

// #define WINDSOR_GOUACHE_PERMANENT_ROSE vec3(0.616, 0.192, 0.263)
// #define PERMANENT_ROSE WINDSOR_GOUACHE_PERMANENT_ROSE

// #define WINDSOR_GOUACHE_PERYLENE_BLACK vec3(0.231, 0.212, 0.208)
// #define PERYLENE_BLACK WINDSOR_GOUACHE_PERYLENE_BLACK

// #define WINDSOR_GOUACHE_PERYLENE_MAROON vec3(0.490, 0.212, 0.271)
// #define PERYLENE_MAROON WINDSOR_GOUACHE_PERYLENE_MAROON

// #define WINDSOR_GOUACHE_PERMANENT_YELLOW_DEEP vec3(1.000, 0.702, 0.000)
// #define PERMANENT_YELLOW_DEEP WINDSOR_GOUACHE_PERMANENT_YELLOW_DEEP

// #define WINDSOR_GOUACHE_PERMANENT_WHITE vec3(1.000, 0.961, 0.984)
// #define PERMANENT_WHITE WINDSOR_GOUACHE_PERMANENT_WHITE

// #define WINDSOR_GOUACHE_PRIMARY_BLUE vec3(0.000, 0.502, 0.796)
// #define PRIMARY_BLUE WINDSOR_GOUACHE_PRIMARY_BLUE

// #define WINDSOR_GOUACHE_PRIMARY_RED vec3(0.769, 0.039, 0.286)
// #define PRIMARY_RED WINDSOR_GOUACHE_PRIMARY_RED

// #define WINDSOR_GOUACHE_PRIMARY_YELLOW vec3(1.000, 0.871, 0.000)
// #define PRIMARY_YELLOW WINDSOR_GOUACHE_PRIMARY_YELLOW

// #define WINDSOR_GOUACHE_PRUSSIAN_BLUE vec3(0.106, 0.251, 0.435)
// #define PRUSSIAN_BLUE WINDSOR_GOUACHE_PRUSSIAN_BLUE

// #define WINDSOR_GOUACHE_RAW_SIENNA vec3(0.749, 0.467, 0.259)
// #define RAW_SIENNA WINDSOR_GOUACHE_RAW_SIENNA

// #define WINDSOR_GOUACHE_RAW_UMBER vec3(0.592, 0.439, 0.290)
// #define RAW_UMBER WINDSOR_GOUACHE_RAW_UMBER

// #define WINDSOR_GOUACHE_RED_OCHRE vec3(0.463, 0.239, 0.255)
// #define RED_OCHRE WINDSOR_GOUACHE_RED_OCHRE

// #define WINDSOR_GOUACHE_ROSE_TYRIEN vec3(0.671, 0.000, 0.416)
// #define ROSE_TYRIEN WINDSOR_GOUACHE_ROSE_TYRIEN

// #define WINDSOR_GOUACHE_SPECTRUM_RED vec3(0.678, 0.235, 0.255)
// #define SPECTRUM_RED WINDSOR_GOUACHE_SPECTRUM_RED

// #define WINDSOR_GOUACHE_SPECTRUM_VIOLET vec3(0.318, 0.200, 0.631)
// #define SPECTRUM_VIOLET WINDSOR_GOUACHE_SPECTRUM_VIOLET

// #define WINDSOR_GOUACHE_ULTRAMARINE vec3(0.192, 0.204, 0.682)
// #define ULTRAMARINE WINDSOR_GOUACHE_ULTRAMARINE

// #define WINDSOR_GOUACHE_ULTRAMARINE_GREEN_SHADE vec3(0.227, 0.427, 0.855)
// #define ULTRAMARINE_GREEN_SHADE WINDSOR_GOUACHE_ULTRAMARINE_GREEN_SHADE

// #define WINDSOR_GOUACHE_VIRIDIAN vec3(0.192, 0.255, 0.255)
// #define VIRIDIAN WINDSOR_GOUACHE_VIRIDIAN

// #define WINDSOR_GOUACHE_WINSOR_BLUE vec3(0.243, 0.196, 0.341)
// #define WINSOR_BLUE WINDSOR_GOUACHE_WINSOR_BLUE

// #define WINDSOR_GOUACHE_WINSOR_GREEN vec3(0.118, 0.325, 0.290)
// #define WINSOR_GREEN WINDSOR_GOUACHE_WINSOR_GREEN

// #define WINDSOR_GOUACHE_WINSOR_VIOLET_DIOXAZINE vec3(0.337, 0.239, 0.486)
// #define WINSOR_VIOLET_DIOXAZINE WINDSOR_GOUACHE_WINSOR_VIOLET_DIOXAZINE

// #define WINDSOR_GOUACHE_YELLOW_OCHRE vec3(0.820, 0.580, 0.294)
// #define YELLOW_OCHRE WINDSOR_GOUACHE_YELLOW_OCHRE

// #define WINDSOR_GOUACHE_ZINC_WHITE vec3(0.965, 0.933, 0.949)
// #define ZINC_WHITE WINDSOR_GOUACHE_ZINC_WHITE
