/*
contributors: Patricio Gonzalez Vivo
description: "RGB colors from Winsor & Newton's acrylic paint colors. \nBased on https://sensuallogic.com/artistcolordata\n"
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/color_pigments.frag
license:
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Prosperity License - https://prosperitylicense.com/versions/3.0.0
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Patron License - https://lygia.xyz/license
*/

#ifndef WINDSOR_ACRYLIC_AZO_YELLOW
#define WINDSOR_ACRYLIC_AZO_YELLOW vec3(1.000, 0.808, 0.000)
#endif
#ifndef AZO_YELLOW
#define AZO_YELLOW WINDSOR_ACRYLIC_AZO_YELLOW
#endif

#ifndef WINDSOR_ACRYLIC_BISMUTH_YELLOW
#define WINDSOR_ACRYLIC_BISMUTH_YELLOW vec3(1.000, 0.922, 0.000)
#endif
#ifndef BISMUTH_YELLOW
#define BISMUTH_YELLOW WINDSOR_ACRYLIC_BISMUTH_YELLOW
#endif

#ifndef WINDSOR_ACRYLIC_AZO_YELLOW_DEEP
#define WINDSOR_ACRYLIC_AZO_YELLOW_DEEP vec3(1.000, 0.608, 0.000)
#endif
#ifndef AZO_YELLOW_DEEP
#define AZO_YELLOW_DEEP WINDSOR_ACRYLIC_AZO_YELLOW_DEEP
#endif

#ifndef WINDSOR_ACRYLIC_BUFF_TITANIUM
#define WINDSOR_ACRYLIC_BUFF_TITANIUM vec3(0.871, 0.729, 0.482)
#endif
#ifndef BUFF_TITANIUM
#define BUFF_TITANIUM WINDSOR_ACRYLIC_BUFF_TITANIUM
#endif

#ifndef WINDSOR_ACRYLIC_BURNT_SIENNA
#define WINDSOR_ACRYLIC_BURNT_SIENNA vec3(0.318, 0.141, 0.094)
#endif
#ifndef BURNT_SIENNA
#define BURNT_SIENNA WINDSOR_ACRYLIC_BURNT_SIENNA
#endif

#ifndef WINDSOR_ACRYLIC_BURNT_UMBER
#define WINDSOR_ACRYLIC_BURNT_UMBER vec3(0.329, 0.196, 0.114)
#endif
#ifndef BURNT_UMBER
#define BURNT_UMBER WINDSOR_ACRYLIC_BURNT_UMBER
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_LEMON
#define WINDSOR_ACRYLIC_CADMIUM_LEMON vec3(1.000, 0.933, 0.071)
#endif
#ifndef CADMIUM_LEMON
#define CADMIUM_LEMON WINDSOR_ACRYLIC_CADMIUM_LEMON
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_ORANGE
#define WINDSOR_ACRYLIC_CADMIUM_ORANGE vec3(1.000, 0.478, 0.000)
#endif
#ifndef CADMIUM_ORANGE
#define CADMIUM_ORANGE WINDSOR_ACRYLIC_CADMIUM_ORANGE
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_RED_DEEP
#define WINDSOR_ACRYLIC_CADMIUM_RED_DEEP vec3(0.667, 0.078, 0.157)
#endif
#ifndef CADMIUM_RED_DEEP
#define CADMIUM_RED_DEEP WINDSOR_ACRYLIC_CADMIUM_RED_DEEP
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_RED
#define WINDSOR_ACRYLIC_CADMIUM_RED vec3(0.416, 0.145, 0.153)
#endif
#ifndef CADMIUM_RED
#define CADMIUM_RED WINDSOR_ACRYLIC_CADMIUM_RED
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_RED_LIGHT
#define WINDSOR_ACRYLIC_CADMIUM_RED_LIGHT vec3(0.902, 0.216, 0.078)
#endif
#ifndef CADMIUM_RED_LIGHT
#define CADMIUM_RED_LIGHT WINDSOR_ACRYLIC_CADMIUM_RED_LIGHT
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_YELLOW_DEEP
#define WINDSOR_ACRYLIC_CADMIUM_YELLOW_DEEP vec3(1.000, 0.710, 0.000)
#endif
#ifndef CADMIUM_YELLOW_DEEP
#define CADMIUM_YELLOW_DEEP WINDSOR_ACRYLIC_CADMIUM_YELLOW_DEEP
#endif

#ifndef WINDSOR_ACRYLIC_CADMIUM_YELLOW
#define WINDSOR_ACRYLIC_CADMIUM_YELLOW vec3(1.000, 0.788, 0.000)
#endif
#ifndef CADMIUM_YELLOW
#define CADMIUM_YELLOW WINDSOR_ACRYLIC_CADMIUM_YELLOW
#endif

#ifndef WINDSOR_ACRYLIC_CERULEAN_BLUE_CHROMIUM
#define WINDSOR_ACRYLIC_CERULEAN_BLUE_CHROMIUM vec3(0.000, 0.353, 0.592)
#endif
#ifndef CERULEAN_BLUE_CHROMIUM
#define CERULEAN_BLUE_CHROMIUM WINDSOR_ACRYLIC_CERULEAN_BLUE_CHROMIUM
#endif

#ifndef WINDSOR_ACRYLIC_CERULEAN_BLUE
#define WINDSOR_ACRYLIC_CERULEAN_BLUE vec3(0.000, 0.424, 0.639)
#endif
#ifndef CERULEAN_BLUE
#define CERULEAN_BLUE WINDSOR_ACRYLIC_CERULEAN_BLUE
#endif

#ifndef WINDSOR_ACRYLIC_CHROMIUM_OXIDE_GREEN
#define WINDSOR_ACRYLIC_CHROMIUM_OXIDE_GREEN vec3(0.298, 0.451, 0.278)
#endif
#ifndef CHROMIUM_OXIDE_GREEN
#define CHROMIUM_OXIDE_GREEN WINDSOR_ACRYLIC_CHROMIUM_OXIDE_GREEN
#endif

#ifndef WINDSOR_ACRYLIC_COBALT_BLUE
#define WINDSOR_ACRYLIC_COBALT_BLUE vec3(0.086, 0.278, 0.600)
#endif
#ifndef COBALT_BLUE
#define COBALT_BLUE WINDSOR_ACRYLIC_COBALT_BLUE
#endif

#ifndef WINDSOR_ACRYLIC_COBALT_BLUE_DEEP
#define WINDSOR_ACRYLIC_COBALT_BLUE_DEEP vec3(0.224, 0.196, 0.490)
#endif
#ifndef COBALT_BLUE_DEEP
#define COBALT_BLUE_DEEP WINDSOR_ACRYLIC_COBALT_BLUE_DEEP
#endif

#ifndef WINDSOR_ACRYLIC_COBALT_GREEN
#define WINDSOR_ACRYLIC_COBALT_GREEN vec3(0.000, 0.514, 0.420)
#endif
#ifndef COBALT_GREEN
#define COBALT_GREEN WINDSOR_ACRYLIC_COBALT_GREEN
#endif

#ifndef WINDSOR_ACRYLIC_COBALT_GREEN_DEEP
#define WINDSOR_ACRYLIC_COBALT_GREEN_DEEP vec3(0.031, 0.322, 0.263)
#endif
#ifndef COBALT_GREEN_DEEP
#define COBALT_GREEN_DEEP WINDSOR_ACRYLIC_COBALT_GREEN_DEEP
#endif

#ifndef WINDSOR_ACRYLIC_COBALT_TURQUOISE_LIGHT
#define WINDSOR_ACRYLIC_COBALT_TURQUOISE_LIGHT vec3(0.000, 0.639, 0.651)
#endif
#ifndef COBALT_TURQUOISE_LIGHT
#define COBALT_TURQUOISE_LIGHT WINDSOR_ACRYLIC_COBALT_TURQUOISE_LIGHT
#endif

#ifndef WINDSOR_ACRYLIC_DAVYS_GRAY
#define WINDSOR_ACRYLIC_DAVYS_GRAY vec3(0.424, 0.396, 0.302)
#endif
#ifndef DAVYS_GRAY
#define DAVYS_GRAY WINDSOR_ACRYLIC_DAVYS_GRAY
#endif

#ifndef WINDSOR_ACRYLIC_DIOXAZINE_PURPLE
#define WINDSOR_ACRYLIC_DIOXAZINE_PURPLE vec3(0.137, 0.114, 0.122)
#endif
#ifndef DIOXAZINE_PURPLE
#define DIOXAZINE_PURPLE WINDSOR_ACRYLIC_DIOXAZINE_PURPLE
#endif

#ifndef WINDSOR_ACRYLIC_GREEN_GOLD
#define WINDSOR_ACRYLIC_GREEN_GOLD vec3(0.263, 0.282, 0.173)
#endif
#ifndef GREEN_GOLD
#define GREEN_GOLD WINDSOR_ACRYLIC_GREEN_GOLD
#endif

#ifndef WINDSOR_ACRYLIC_HOOKERS_GREEN
#define WINDSOR_ACRYLIC_HOOKERS_GREEN vec3(0.204, 0.251, 0.149)
#endif
#ifndef HOOKERS_GREEN
#define HOOKERS_GREEN WINDSOR_ACRYLIC_HOOKERS_GREEN
#endif

#ifndef WINDSOR_ACRYLIC_INDANTHRENE_BLUE
#define WINDSOR_ACRYLIC_INDANTHRENE_BLUE vec3(0.133, 0.082, 0.141)
#endif
#ifndef INDANTHRENE_BLUE
#define INDANTHRENE_BLUE WINDSOR_ACRYLIC_INDANTHRENE_BLUE
#endif

#ifndef WINDSOR_ACRYLIC_IVORY_BLACK
#define WINDSOR_ACRYLIC_IVORY_BLACK vec3(0.161, 0.161, 0.161)
#endif
#ifndef IVORY_BLACK
#define IVORY_BLACK WINDSOR_ACRYLIC_IVORY_BLACK
#endif

#ifndef WINDSOR_ACRYLIC_LEMON_YELLOW
#define WINDSOR_ACRYLIC_LEMON_YELLOW vec3(0.953, 0.878, 0.000)
#endif
#ifndef LEMON_YELLOW
#define LEMON_YELLOW WINDSOR_ACRYLIC_LEMON_YELLOW
#endif

#ifndef WINDSOR_ACRYLIC_LIGHT_RED
#define WINDSOR_ACRYLIC_LIGHT_RED vec3(0.620, 0.294, 0.208)
#endif
#ifndef LIGHT_RED
#define LIGHT_RED WINDSOR_ACRYLIC_LIGHT_RED
#endif

#ifndef WINDSOR_ACRYLIC_MARS_BLACK
#define WINDSOR_ACRYLIC_MARS_BLACK vec3(0.180, 0.176, 0.173)
#endif
#ifndef MARS_BLACK
#define MARS_BLACK WINDSOR_ACRYLIC_MARS_BLACK
#endif

#ifndef WINDSOR_ACRYLIC_NAPHTHOL_RED_LIGHT
#define WINDSOR_ACRYLIC_NAPHTHOL_RED_LIGHT vec3(0.737, 0.055, 0.012)
#endif
#ifndef NAPHTHOL_RED_LIGHT
#define NAPHTHOL_RED_LIGHT WINDSOR_ACRYLIC_NAPHTHOL_RED_LIGHT
#endif

#ifndef WINDSOR_ACRYLIC_NAPHTHOL_RED
#define WINDSOR_ACRYLIC_NAPHTHOL_RED vec3(0.686, 0.000, 0.027)
#endif
#ifndef NAPHTHOL_RED
#define NAPHTHOL_RED WINDSOR_ACRYLIC_NAPHTHOL_RED
#endif

#ifndef WINDSOR_ACRYLIC_NAPLES_YELLOW_DEEP
#define WINDSOR_ACRYLIC_NAPLES_YELLOW_DEEP vec3(0.922, 0.647, 0.247)
#endif
#ifndef NAPLES_YELLOW_DEEP
#define NAPLES_YELLOW_DEEP WINDSOR_ACRYLIC_NAPLES_YELLOW_DEEP
#endif

#ifndef WINDSOR_ACRYLIC_NICKEL_AZO_YELLOW
#define WINDSOR_ACRYLIC_NICKEL_AZO_YELLOW vec3(0.514, 0.361, 0.008)
#endif
#ifndef NICKEL_AZO_YELLOW
#define NICKEL_AZO_YELLOW WINDSOR_ACRYLIC_NICKEL_AZO_YELLOW
#endif

#ifndef WINDSOR_ACRYLIC_OLIVE_GREEN
#define WINDSOR_ACRYLIC_OLIVE_GREEN vec3(0.161, 0.196, 0.133)
#endif
#ifndef OLIVE_GREEN
#define OLIVE_GREEN WINDSOR_ACRYLIC_OLIVE_GREEN
#endif

#ifndef WINDSOR_ACRYLIC_PERYLENE_GREEN
#define WINDSOR_ACRYLIC_PERYLENE_GREEN vec3(0.153, 0.125, 0.125)
#endif
#ifndef PERYLENE_GREEN
#define PERYLENE_GREEN WINDSOR_ACRYLIC_PERYLENE_GREEN
#endif

#ifndef WINDSOR_ACRYLIC_PERYLENE_RED
#define WINDSOR_ACRYLIC_PERYLENE_RED vec3(0.545, 0.000, 0.078)
#endif
#ifndef PERYLENE_RED
#define PERYLENE_RED WINDSOR_ACRYLIC_PERYLENE_RED
#endif

#ifndef WINDSOR_ACRYLIC_PERMANENT_ALIZARIN_CRIMSON
#define WINDSOR_ACRYLIC_PERMANENT_ALIZARIN_CRIMSON vec3(0.349, 0.102, 0.133)
#endif
#ifndef PERMANENT_ALIZARIN_CRIMSON
#define PERMANENT_ALIZARIN_CRIMSON WINDSOR_ACRYLIC_PERMANENT_ALIZARIN_CRIMSON
#endif

#ifndef WINDSOR_ACRYLIC_PERYLENE_VIOLET
#define WINDSOR_ACRYLIC_PERYLENE_VIOLET vec3(0.227, 0.086, 0.090)
#endif
#ifndef PERYLENE_VIOLET
#define PERYLENE_VIOLET WINDSOR_ACRYLIC_PERYLENE_VIOLET
#endif

#ifndef WINDSOR_ACRYLIC_PERMANENT_SAP_GREEN
#define WINDSOR_ACRYLIC_PERMANENT_SAP_GREEN vec3(0.094, 0.149, 0.082)
#endif
#ifndef PERMANENT_SAP_GREEN
#define PERMANENT_SAP_GREEN WINDSOR_ACRYLIC_PERMANENT_SAP_GREEN
#endif

#ifndef WINDSOR_ACRYLIC_PERYLENE_MAROON
#define WINDSOR_ACRYLIC_PERYLENE_MAROON vec3(0.298, 0.078, 0.086)
#endif
#ifndef PERYLENE_MAROON
#define PERYLENE_MAROON WINDSOR_ACRYLIC_PERYLENE_MAROON
#endif

#ifndef WINDSOR_ACRYLIC_PHTHALO_BLUE_RED_SHADE
#define WINDSOR_ACRYLIC_PHTHALO_BLUE_RED_SHADE vec3(0.098, 0.055, 0.227)
#endif
#ifndef PHTHALO_BLUE_RED_SHADE
#define PHTHALO_BLUE_RED_SHADE WINDSOR_ACRYLIC_PHTHALO_BLUE_RED_SHADE
#endif

#ifndef WINDSOR_ACRYLIC_PHTHALO_BLUE_GREEN_SHADE
#define WINDSOR_ACRYLIC_PHTHALO_BLUE_GREEN_SHADE vec3(0.063, 0.141, 0.208)
#endif
#ifndef PHTHALO_BLUE_GREEN_SHADE
#define PHTHALO_BLUE_GREEN_SHADE WINDSOR_ACRYLIC_PHTHALO_BLUE_GREEN_SHADE
#endif

#ifndef WINDSOR_ACRYLIC_PYRROLE_ORANGE
#define WINDSOR_ACRYLIC_PYRROLE_ORANGE vec3(0.957, 0.259, 0.000)
#endif
#ifndef PYRROLE_ORANGE
#define PYRROLE_ORANGE WINDSOR_ACRYLIC_PYRROLE_ORANGE
#endif

#ifndef WINDSOR_ACRYLIC_PHTHALO_GREEN_YELLOW_SHADE
#define WINDSOR_ACRYLIC_PHTHALO_GREEN_YELLOW_SHADE vec3(0.000, 0.184, 0.165)
#endif
#ifndef PHTHALO_GREEN_YELLOW_SHADE
#define PHTHALO_GREEN_YELLOW_SHADE WINDSOR_ACRYLIC_PHTHALO_GREEN_YELLOW_SHADE
#endif

#ifndef WINDSOR_ACRYLIC_PHTHALO_GREEN_BLUE_SHADE
#define WINDSOR_ACRYLIC_PHTHALO_GREEN_BLUE_SHADE vec3(0.008, 0.129, 0.153)
#endif
#ifndef PHTHALO_GREEN_BLUE_SHADE
#define PHTHALO_GREEN_BLUE_SHADE WINDSOR_ACRYLIC_PHTHALO_GREEN_BLUE_SHADE
#endif

#ifndef WINDSOR_ACRYLIC_PHTHALO_TURQUOISE
#define WINDSOR_ACRYLIC_PHTHALO_TURQUOISE vec3(0.000, 0.216, 0.235)
#endif
#ifndef PHTHALO_TURQUOISE
#define PHTHALO_TURQUOISE WINDSOR_ACRYLIC_PHTHALO_TURQUOISE
#endif

#ifndef WINDSOR_ACRYLIC_PYRROLE_RED
#define WINDSOR_ACRYLIC_PYRROLE_RED vec3(0.757, 0.000, 0.110)
#endif
#ifndef PYRROLE_RED
#define PYRROLE_RED WINDSOR_ACRYLIC_PYRROLE_RED
#endif

#ifndef WINDSOR_ACRYLIC_PYRROLE_RED_LIGHT
#define WINDSOR_ACRYLIC_PYRROLE_RED_LIGHT vec3(0.843, 0.133, 0.133)
#endif
#ifndef PYRROLE_RED_LIGHT
#define PYRROLE_RED_LIGHT WINDSOR_ACRYLIC_PYRROLE_RED_LIGHT
#endif

#ifndef WINDSOR_ACRYLIC_POTTERS_PINK
#define WINDSOR_ACRYLIC_POTTERS_PINK vec3(0.506, 0.263, 0.306)
#endif
#ifndef POTTERS_PINK
#define POTTERS_PINK WINDSOR_ACRYLIC_POTTERS_PINK
#endif

#ifndef WINDSOR_ACRYLIC_QUINACRIDONE_MAGENTA
#define WINDSOR_ACRYLIC_QUINACRIDONE_MAGENTA vec3(0.306, 0.067, 0.122)
#endif
#ifndef QUINACRIDONE_MAGENTA
#define QUINACRIDONE_MAGENTA WINDSOR_ACRYLIC_QUINACRIDONE_MAGENTA
#endif

#ifndef WINDSOR_ACRYLIC_QUINACRIDONE_RED
#define WINDSOR_ACRYLIC_QUINACRIDONE_RED vec3(0.604, 0.082, 0.141)
#endif
#ifndef QUINACRIDONE_RED
#define QUINACRIDONE_RED WINDSOR_ACRYLIC_QUINACRIDONE_RED
#endif

#ifndef WINDSOR_ACRYLIC_QUINACRIDONE_BURNT_ORANGE
#define WINDSOR_ACRYLIC_QUINACRIDONE_BURNT_ORANGE vec3(0.290, 0.141, 0.137)
#endif
#ifndef QUINACRIDONE_BURNT_ORANGE
#define QUINACRIDONE_BURNT_ORANGE WINDSOR_ACRYLIC_QUINACRIDONE_BURNT_ORANGE
#endif

#ifndef WINDSOR_ACRYLIC_QUINACRIDONE_VIOLET
#define WINDSOR_ACRYLIC_QUINACRIDONE_VIOLET vec3(0.376, 0.086, 0.184)
#endif
#ifndef QUINACRIDONE_VIOLET
#define QUINACRIDONE_VIOLET WINDSOR_ACRYLIC_QUINACRIDONE_VIOLET
#endif

#ifndef WINDSOR_ACRYLIC_RAW_SIENNA
#define WINDSOR_ACRYLIC_RAW_SIENNA vec3(0.435, 0.271, 0.110)
#endif
#ifndef RAW_SIENNA
#define RAW_SIENNA WINDSOR_ACRYLIC_RAW_SIENNA
#endif

#ifndef WINDSOR_ACRYLIC_RAW_UMBER
#define WINDSOR_ACRYLIC_RAW_UMBER vec3(0.243, 0.212, 0.180)
#endif
#ifndef RAW_UMBER
#define RAW_UMBER WINDSOR_ACRYLIC_RAW_UMBER
#endif

#ifndef WINDSOR_ACRYLIC_TITANIUM_WHITE
#define WINDSOR_ACRYLIC_TITANIUM_WHITE vec3(0.992, 0.996, 0.976)
#endif
#ifndef TITANIUM_WHITE
#define TITANIUM_WHITE WINDSOR_ACRYLIC_TITANIUM_WHITE
#endif

#ifndef WINDSOR_ACRYLIC_ULTRAMARINE_BLUE
#define WINDSOR_ACRYLIC_ULTRAMARINE_BLUE vec3(0.208, 0.188, 0.325)
#endif
#ifndef ULTRAMARINE_BLUE
#define ULTRAMARINE_BLUE WINDSOR_ACRYLIC_ULTRAMARINE_BLUE
#endif

#ifndef WINDSOR_ACRYLIC_ULTRAMARINE_VIOLET
#define WINDSOR_ACRYLIC_ULTRAMARINE_VIOLET vec3(0.212, 0.204, 0.267)
#endif
#ifndef ULTRAMARINE_VIOLET
#define ULTRAMARINE_VIOLET WINDSOR_ACRYLIC_ULTRAMARINE_VIOLET
#endif

#ifndef WINDSOR_ACRYLIC_YELLOW_OCHRE
#define WINDSOR_ACRYLIC_YELLOW_OCHRE vec3(0.635, 0.427, 0.200)
#endif
#ifndef YELLOW_OCHRE
#define YELLOW_OCHRE WINDSOR_ACRYLIC_YELLOW_OCHRE
#endif

