/*
contributors: Patricio Gonzalez Vivo
description: "RGB colors from Winsor & Newton's gouache paint colors. \nBased on https://sensuallogic.com/artistcolordata\n"
examples:
    - https://raw.githubusercontent.com/patriciogonzalezvivo/lygia_examples/main/color_pigments.frag
license:
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Prosperity License - https://prosperitylicense.com/versions/3.0.0
    - Copyright (c) 2021 Patricio Gonzalez Vivo under Patron License - https://lygia.xyz/license
*/

#ifndef WINDSOR_GOUACHE_ALIZARIN_CRIMSON
#define WINDSOR_GOUACHE_ALIZARIN_CRIMSON float3(0.604, 0.173, 0.263)
#endif
#ifndef ALIZARIN_CRIMSON
#define ALIZARIN_CRIMSON WINDSOR_GOUACHE_ALIZARIN_CRIMSON
#endif

#ifndef WINDSOR_GOUACHE_BURNT_SIENNA
#define WINDSOR_GOUACHE_BURNT_SIENNA float3(0.569, 0.298, 0.212)
#endif
#ifndef BURNT_SIENNA
#define BURNT_SIENNA WINDSOR_GOUACHE_BURNT_SIENNA
#endif

#ifndef WINDSOR_GOUACHE_BURNT_UMBER
#define WINDSOR_GOUACHE_BURNT_UMBER float3(0.408, 0.282, 0.239)
#endif
#ifndef BURNT_UMBER
#define BURNT_UMBER WINDSOR_GOUACHE_BURNT_UMBER
#endif

#ifndef WINDSOR_GOUACHE_CADMIUM_LEMON
#define WINDSOR_GOUACHE_CADMIUM_LEMON float3(1.000, 0.898, 0.180)
#endif
#ifndef CADMIUM_LEMON
#define CADMIUM_LEMON WINDSOR_GOUACHE_CADMIUM_LEMON
#endif

#ifndef WINDSOR_GOUACHE_CADMIUM_ORANGE
#define WINDSOR_GOUACHE_CADMIUM_ORANGE float3(0.992, 0.435, 0.165)
#endif
#ifndef CADMIUM_ORANGE
#define CADMIUM_ORANGE WINDSOR_GOUACHE_CADMIUM_ORANGE
#endif

#ifndef WINDSOR_GOUACHE_CADMIUM_RED
#define WINDSOR_GOUACHE_CADMIUM_RED float3(0.824, 0.231, 0.216)
#endif
#ifndef CADMIUM_RED
#define CADMIUM_RED WINDSOR_GOUACHE_CADMIUM_RED
#endif

#ifndef WINDSOR_GOUACHE_CADMIUM_SCARLET
#define WINDSOR_GOUACHE_CADMIUM_SCARLET float3(0.914, 0.271, 0.184)
#endif
#ifndef CADMIUM_SCARLET
#define CADMIUM_SCARLET WINDSOR_GOUACHE_CADMIUM_SCARLET
#endif

#ifndef WINDSOR_GOUACHE_CADMIUM_YELLOW
#define WINDSOR_GOUACHE_CADMIUM_YELLOW float3(1.000, 0.741, 0.000)
#endif
#ifndef CADMIUM_YELLOW
#define CADMIUM_YELLOW WINDSOR_GOUACHE_CADMIUM_YELLOW
#endif

#ifndef WINDSOR_GOUACHE_CERULEAN_BLUE
#define WINDSOR_GOUACHE_CERULEAN_BLUE float3(0.063, 0.459, 0.655)
#endif
#ifndef CERULEAN_BLUE
#define CERULEAN_BLUE WINDSOR_GOUACHE_CERULEAN_BLUE
#endif

#ifndef WINDSOR_GOUACHE_COBALT_BLUE
#define WINDSOR_GOUACHE_COBALT_BLUE float3(0.129, 0.408, 0.788)
#endif
#ifndef COBALT_BLUE
#define COBALT_BLUE WINDSOR_GOUACHE_COBALT_BLUE
#endif

#ifndef WINDSOR_GOUACHE_COBALT_TURQUOISE_LIGHT
#define WINDSOR_GOUACHE_COBALT_TURQUOISE_LIGHT float3(0.000, 0.651, 0.694)
#endif
#ifndef COBALT_TURQUOISE_LIGHT
#define COBALT_TURQUOISE_LIGHT WINDSOR_GOUACHE_COBALT_TURQUOISE_LIGHT
#endif

#ifndef WINDSOR_GOUACHE_FLAME_RED
#define WINDSOR_GOUACHE_FLAME_RED float3(0.824, 0.251, 0.208)
#endif
#ifndef FLAME_RED
#define FLAME_RED WINDSOR_GOUACHE_FLAME_RED
#endif

#ifndef WINDSOR_GOUACHE_INDIGO
#define WINDSOR_GOUACHE_INDIGO float3(0.220, 0.231, 0.345)
#endif
#ifndef INDIGO
#define INDIGO WINDSOR_GOUACHE_INDIGO
#endif

#ifndef WINDSOR_GOUACHE_IVORY_BLACK
#define WINDSOR_GOUACHE_IVORY_BLACK float3(0.173, 0.161, 0.169)
#endif
#ifndef IVORY_BLACK
#define IVORY_BLACK WINDSOR_GOUACHE_IVORY_BLACK
#endif

#ifndef WINDSOR_GOUACHE_JET_BLACK
#define WINDSOR_GOUACHE_JET_BLACK float3(0.153, 0.129, 0.137)
#endif
#ifndef JET_BLACK
#define JET_BLACK WINDSOR_GOUACHE_JET_BLACK
#endif

#ifndef WINDSOR_GOUACHE_LAMP_BLACK
#define WINDSOR_GOUACHE_LAMP_BLACK float3(0.224, 0.220, 0.235)
#endif
#ifndef LAMP_BLACK
#define LAMP_BLACK WINDSOR_GOUACHE_LAMP_BLACK
#endif

#ifndef WINDSOR_GOUACHE_LEMON_YELLOW
#define WINDSOR_GOUACHE_LEMON_YELLOW float3(1.000, 0.918, 0.047)
#endif
#ifndef LEMON_YELLOW
#define LEMON_YELLOW WINDSOR_GOUACHE_LEMON_YELLOW
#endif

#ifndef WINDSOR_GOUACHE_LIGHT_PURPLE
#define WINDSOR_GOUACHE_LIGHT_PURPLE float3(0.451, 0.224, 0.596)
#endif
#ifndef LIGHT_PURPLE
#define LIGHT_PURPLE WINDSOR_GOUACHE_LIGHT_PURPLE
#endif

#ifndef WINDSOR_GOUACHE_MAGENTA
#define WINDSOR_GOUACHE_MAGENTA float3(0.467, 0.196, 0.459)
#endif
#ifndef MAGENTA
#define MAGENTA WINDSOR_GOUACHE_MAGENTA
#endif

#ifndef WINDSOR_GOUACHE_MARIGOLD_YELLOW
#define WINDSOR_GOUACHE_MARIGOLD_YELLOW float3(1.000, 0.471, 0.110)
#endif
#ifndef MARIGOLD_YELLOW
#define MARIGOLD_YELLOW WINDSOR_GOUACHE_MARIGOLD_YELLOW
#endif

#ifndef WINDSOR_GOUACHE_NAPLES_YELLOW_DEEP
#define WINDSOR_GOUACHE_NAPLES_YELLOW_DEEP float3(0.875, 0.604, 0.282)
#endif
#ifndef NAPLES_YELLOW_DEEP
#define NAPLES_YELLOW_DEEP WINDSOR_GOUACHE_NAPLES_YELLOW_DEEP
#endif

#ifndef WINDSOR_GOUACHE_ORANGE_LAKE_LIGHT
#define WINDSOR_GOUACHE_ORANGE_LAKE_LIGHT float3(0.929, 0.376, 0.184)
#endif
#ifndef ORANGE_LAKE_LIGHT
#define ORANGE_LAKE_LIGHT WINDSOR_GOUACHE_ORANGE_LAKE_LIGHT
#endif

#ifndef WINDSOR_GOUACHE_OXIDE_OF_CHROMIUM
#define WINDSOR_GOUACHE_OXIDE_OF_CHROMIUM float3(0.306, 0.420, 0.322)
#endif
#ifndef OXIDE_OF_CHROMIUM
#define OXIDE_OF_CHROMIUM WINDSOR_GOUACHE_OXIDE_OF_CHROMIUM
#endif

#ifndef WINDSOR_GOUACHE_PERMANENT_ALIZARIN_CRIMSON
#define WINDSOR_GOUACHE_PERMANENT_ALIZARIN_CRIMSON float3(0.612, 0.173, 0.235)
#endif
#ifndef PERMANENT_ALIZARIN_CRIMSON
#define PERMANENT_ALIZARIN_CRIMSON WINDSOR_GOUACHE_PERMANENT_ALIZARIN_CRIMSON
#endif

#ifndef WINDSOR_GOUACHE_PERYLENE_VIOLET
#define WINDSOR_GOUACHE_PERYLENE_VIOLET float3(0.298, 0.208, 0.259)
#endif
#ifndef PERYLENE_VIOLET
#define PERYLENE_VIOLET WINDSOR_GOUACHE_PERYLENE_VIOLET
#endif

#ifndef WINDSOR_GOUACHE_PERMANENT_ROSE
#define WINDSOR_GOUACHE_PERMANENT_ROSE float3(0.616, 0.192, 0.263)
#endif
#ifndef PERMANENT_ROSE
#define PERMANENT_ROSE WINDSOR_GOUACHE_PERMANENT_ROSE
#endif

#ifndef WINDSOR_GOUACHE_PERYLENE_BLACK
#define WINDSOR_GOUACHE_PERYLENE_BLACK float3(0.231, 0.212, 0.208)
#endif
#ifndef PERYLENE_BLACK
#define PERYLENE_BLACK WINDSOR_GOUACHE_PERYLENE_BLACK
#endif

#ifndef WINDSOR_GOUACHE_PERYLENE_MAROON
#define WINDSOR_GOUACHE_PERYLENE_MAROON float3(0.490, 0.212, 0.271)
#endif
#ifndef PERYLENE_MAROON
#define PERYLENE_MAROON WINDSOR_GOUACHE_PERYLENE_MAROON
#endif

#ifndef WINDSOR_GOUACHE_PERMANENT_YELLOW_DEEP
#define WINDSOR_GOUACHE_PERMANENT_YELLOW_DEEP float3(1.000, 0.702, 0.000)
#endif
#ifndef PERMANENT_YELLOW_DEEP
#define PERMANENT_YELLOW_DEEP WINDSOR_GOUACHE_PERMANENT_YELLOW_DEEP
#endif

#ifndef WINDSOR_GOUACHE_PERMANENT_WHITE
#define WINDSOR_GOUACHE_PERMANENT_WHITE float3(1.000, 0.961, 0.984)
#endif
#ifndef PERMANENT_WHITE
#define PERMANENT_WHITE WINDSOR_GOUACHE_PERMANENT_WHITE
#endif

#ifndef WINDSOR_GOUACHE_PRIMARY_BLUE
#define WINDSOR_GOUACHE_PRIMARY_BLUE float3(0.000, 0.502, 0.796)
#endif
#ifndef PRIMARY_BLUE
#define PRIMARY_BLUE WINDSOR_GOUACHE_PRIMARY_BLUE
#endif

#ifndef WINDSOR_GOUACHE_PRIMARY_RED
#define WINDSOR_GOUACHE_PRIMARY_RED float3(0.769, 0.039, 0.286)
#endif
#ifndef PRIMARY_RED
#define PRIMARY_RED WINDSOR_GOUACHE_PRIMARY_RED
#endif

#ifndef WINDSOR_GOUACHE_PRIMARY_YELLOW
#define WINDSOR_GOUACHE_PRIMARY_YELLOW float3(1.000, 0.871, 0.000)
#endif
#ifndef PRIMARY_YELLOW
#define PRIMARY_YELLOW WINDSOR_GOUACHE_PRIMARY_YELLOW
#endif

#ifndef WINDSOR_GOUACHE_PRUSSIAN_BLUE
#define WINDSOR_GOUACHE_PRUSSIAN_BLUE float3(0.106, 0.251, 0.435)
#endif
#ifndef PRUSSIAN_BLUE
#define PRUSSIAN_BLUE WINDSOR_GOUACHE_PRUSSIAN_BLUE
#endif

#ifndef WINDSOR_GOUACHE_RAW_SIENNA
#define WINDSOR_GOUACHE_RAW_SIENNA float3(0.749, 0.467, 0.259)
#endif
#ifndef RAW_SIENNA
#define RAW_SIENNA WINDSOR_GOUACHE_RAW_SIENNA
#endif

#ifndef WINDSOR_GOUACHE_RAW_UMBER
#define WINDSOR_GOUACHE_RAW_UMBER float3(0.592, 0.439, 0.290)
#endif
#ifndef RAW_UMBER
#define RAW_UMBER WINDSOR_GOUACHE_RAW_UMBER
#endif

#ifndef WINDSOR_GOUACHE_RED_OCHRE
#define WINDSOR_GOUACHE_RED_OCHRE float3(0.463, 0.239, 0.255)
#endif
#ifndef RED_OCHRE
#define RED_OCHRE WINDSOR_GOUACHE_RED_OCHRE
#endif

#ifndef WINDSOR_GOUACHE_ROSE_TYRIEN
#define WINDSOR_GOUACHE_ROSE_TYRIEN float3(0.671, 0.000, 0.416)
#endif
#ifndef ROSE_TYRIEN
#define ROSE_TYRIEN WINDSOR_GOUACHE_ROSE_TYRIEN
#endif

#ifndef WINDSOR_GOUACHE_SPECTRUM_RED
#define WINDSOR_GOUACHE_SPECTRUM_RED float3(0.678, 0.235, 0.255)
#endif
#ifndef SPECTRUM_RED
#define SPECTRUM_RED WINDSOR_GOUACHE_SPECTRUM_RED
#endif

#ifndef WINDSOR_GOUACHE_SPECTRUM_VIOLET
#define WINDSOR_GOUACHE_SPECTRUM_VIOLET float3(0.318, 0.200, 0.631)
#endif
#ifndef SPECTRUM_VIOLET
#define SPECTRUM_VIOLET WINDSOR_GOUACHE_SPECTRUM_VIOLET
#endif

#ifndef WINDSOR_GOUACHE_ULTRAMARINE
#define WINDSOR_GOUACHE_ULTRAMARINE float3(0.192, 0.204, 0.682)
#endif
#ifndef ULTRAMARINE
#define ULTRAMARINE WINDSOR_GOUACHE_ULTRAMARINE
#endif

#ifndef WINDSOR_GOUACHE_ULTRAMARINE_GREEN_SHADE
#define WINDSOR_GOUACHE_ULTRAMARINE_GREEN_SHADE float3(0.227, 0.427, 0.855)
#endif
#ifndef ULTRAMARINE_GREEN_SHADE
#define ULTRAMARINE_GREEN_SHADE WINDSOR_GOUACHE_ULTRAMARINE_GREEN_SHADE
#endif

#ifndef WINDSOR_GOUACHE_VIRIDIAN
#define WINDSOR_GOUACHE_VIRIDIAN float3(0.192, 0.255, 0.255)
#endif
#ifndef VIRIDIAN
#define VIRIDIAN WINDSOR_GOUACHE_VIRIDIAN
#endif

#ifndef WINDSOR_GOUACHE_WINSOR_BLUE
#define WINDSOR_GOUACHE_WINSOR_BLUE float3(0.243, 0.196, 0.341)
#endif
#ifndef WINSOR_BLUE
#define WINSOR_BLUE WINDSOR_GOUACHE_WINSOR_BLUE
#endif

#ifndef WINDSOR_GOUACHE_WINSOR_GREEN
#define WINDSOR_GOUACHE_WINSOR_GREEN float3(0.118, 0.325, 0.290)
#endif
#ifndef WINSOR_GREEN
#define WINSOR_GREEN WINDSOR_GOUACHE_WINSOR_GREEN
#endif

#ifndef WINDSOR_GOUACHE_WINSOR_VIOLET_DIOXAZINE
#define WINDSOR_GOUACHE_WINSOR_VIOLET_DIOXAZINE float3(0.337, 0.239, 0.486)
#endif
#ifndef WINSOR_VIOLET_DIOXAZINE
#define WINSOR_VIOLET_DIOXAZINE WINDSOR_GOUACHE_WINSOR_VIOLET_DIOXAZINE
#endif

#ifndef WINDSOR_GOUACHE_YELLOW_OCHRE
#define WINDSOR_GOUACHE_YELLOW_OCHRE float3(0.820, 0.580, 0.294)
#endif
#ifndef YELLOW_OCHRE
#define YELLOW_OCHRE WINDSOR_GOUACHE_YELLOW_OCHRE
#endif

#ifndef WINDSOR_GOUACHE_ZINC_WHITE
#define WINDSOR_GOUACHE_ZINC_WHITE float3(0.965, 0.933, 0.949)
#endif
#ifndef ZINC_WHITE
#define ZINC_WHITE WINDSOR_GOUACHE_ZINC_WHITE
#endif

